platform: aws

image:
  repository: <account-id>.dkr.ecr.<region>.amazonaws.com/nuages-operator

serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::<account-id>:role/nuages-operator"

nodeSelector:
  kubernetes.io/os: linux
  kubernetes.io/arch: amd64

defaults:
  database:
    instance_class: db.t3.micro
    storage_gb: 20
    multi_az: false
    engine_version:
      postgresql: "16.3"
      mysql: "8.0"
  cache:
    node_type: cache.t3.micro
    num_nodes: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  storage:
    class: gp3
  ingress:
    class: alb
    annotations:
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/scheme: internet-facing
