//! Dockerfile auto-generation for reinhardt-web applications.

mod cargo_lock_reader;
mod dockerfile;
mod rust_toolchain_reader;
mod stages;

use std::path::{Path, PathBuf};

use reinhardt_cloud_types::reinhardt_cloud_toml::ReinhardtCloudToml;

/// Walk from `start_dir` upward looking for a file with the given name.
/// Returns the closest match, or `None` if no parent directory contains it.
/// Used so workspace-level files (`Cargo.lock`, `rust-toolchain.toml`) can
/// be located when `init` is invoked from a member crate directory.
fn locate_ancestor_file(start_dir: &Path, file_name: &str) -> Option<PathBuf> {
	let mut current = start_dir.canonicalize().ok()?;
	loop {
		let candidate = current.join(file_name);
		if candidate.exists() {
			return Some(candidate);
		}
		current = current.parent()?.to_path_buf();
	}
}

pub(crate) use self::dockerfile::Dockerfile;
pub(crate) use self::stages::DockerfileSignals;

use self::stages::{build_builder_stage, build_chef_stage, build_runtime_stage, build_wasm_stage};

/// Reason why Dockerfile generation was skipped.
#[derive(Debug, PartialEq)]
pub(crate) enum SkipReason {
	/// No skip — generate the Dockerfile.
	None,
	/// User has a custom Dockerfile path in `[source.build].dockerfile`.
	CustomDockerfile,
	/// Dockerfile already exists and `--force` was not specified.
	AlreadyExists,
}

/// Returns `true` if the path refers to the default Dockerfile location.
fn is_default_dockerfile_path(path: &str) -> bool {
	matches!(path, "Dockerfile" | "./Dockerfile")
}

/// Check whether Dockerfile generation should be skipped.
pub(crate) fn should_skip_dockerfile(
	project_dir: &Path,
	toml_config: &ReinhardtCloudToml,
	force: bool,
) -> SkipReason {
	// Check custom dockerfile path (skip default names)
	if let Some(source) = &toml_config.source
		&& let Some(build) = &source.build
		&& let Some(df) = &build.dockerfile
		&& !df.is_empty()
		&& !is_default_dockerfile_path(df)
	{
		return SkipReason::CustomDockerfile;
	}

	// Check if Dockerfile already exists
	if project_dir.join("Dockerfile").exists() && !force {
		return SkipReason::AlreadyExists;
	}

	SkipReason::None
}

/// Collect all signals needed for Dockerfile generation.
pub(crate) fn collect_signals(
	project_dir: &Path,
	metadata: &crate::feature_detector::ProjectMetadata,
	toml_config: &ReinhardtCloudToml,
) -> Result<DockerfileSignals, String> {
	let rust_version = rust_toolchain_reader::read_rust_version(project_dir)?;

	let signals = &metadata.signals;

	// wasm-bindgen version: Cargo.lock > reinhardt-cloud.toml build_args.
	// Cargo.lock lives at the workspace root in workspace projects, not in
	// the member crate, so walk up if not found locally.
	let wasm_bindgen_version = if signals.pages {
		let from_lock = if let Some(lock_path) = locate_ancestor_file(project_dir, "Cargo.lock") {
			let content = std::fs::read_to_string(&lock_path)
				.map_err(|e| format!("failed to read {}: {e}", lock_path.display()))?;
			cargo_lock_reader::extract_wasm_bindgen_version(&content)?
		} else {
			None
		};

		let version = from_lock.or_else(|| {
			// Fallback: check reinhardt-cloud.toml build_args
			toml_config
				.source
				.as_ref()
				.and_then(|s| s.build.as_ref())
				.and_then(|b| b.build_args.get("WASM_BINDGEN_VERSION").cloned())
		});

		if version.is_none() {
			return Err("pages feature detected but wasm-bindgen version not found \
				 in Cargo.lock or reinhardt-cloud.toml"
				.to_string());
		}
		version
	} else {
		None
	};

	// base_image override
	let base_image_override = toml_config
		.source
		.as_ref()
		.and_then(|s| s.build.as_ref())
		.and_then(|b| b.base_image.clone());

	Ok(DockerfileSignals {
		app_name: metadata.name.clone(),
		rust_version,
		pages: signals.pages,
		grpc: signals.grpc,
		graphql: signals.graphql,
		wasm_bindgen_version,
		database: signals.database.clone(),
		cache: signals.cache.clone(),
		session_backend: None, // Only available via introspect at deploy time
		base_image_override,
		tracing: signals.tracing,
	})
}

/// Generate a Dockerfile from signals.
pub(crate) fn generate(signals: &DockerfileSignals) -> Dockerfile {
	let mut stages = vec![build_chef_stage(signals), build_builder_stage(signals)];

	if signals.pages {
		stages.push(build_wasm_stage(signals));
	}

	stages.push(build_runtime_stage(signals));

	Dockerfile {
		header_comment: "Generated by reinhardt-cloud. Do not edit manually.".to_string(),
		stages,
	}
}

#[cfg(test)]
mod tests {
	use super::*;
	use reinhardt_cloud_types::reinhardt_cloud_toml::{BuildSection, SourceSection};
	use rstest::*;

	fn minimal_signals() -> DockerfileSignals {
		DockerfileSignals {
			app_name: "my-app".to_string(),
			rust_version: "1.94.1".to_string(),
			pages: false,
			grpc: false,
			graphql: false,
			wasm_bindgen_version: None,
			database: None,
			cache: None,
			session_backend: None,
			base_image_override: None,
			tracing: false,
		}
	}

	// G1
	#[rstest]
	fn snapshot_api_minimal() {
		let df = generate(&minimal_signals());
		assert_eq!(
			df.to_string(),
			include_str!("dockerfile_generator/snapshots/api_minimal.dockerfile")
		);
	}

	// G2
	#[rstest]
	fn snapshot_api_postgres() {
		let signals = DockerfileSignals {
			database: Some("postgresql".into()),
			..minimal_signals()
		};
		assert_eq!(
			generate(&signals).to_string(),
			include_str!("dockerfile_generator/snapshots/api_postgres.dockerfile")
		);
	}

	// G3
	#[rstest]
	fn snapshot_api_mysql() {
		let signals = DockerfileSignals {
			database: Some("mysql".into()),
			..minimal_signals()
		};
		assert_eq!(
			generate(&signals).to_string(),
			include_str!("dockerfile_generator/snapshots/api_mysql.dockerfile")
		);
	}

	// G4
	#[rstest]
	fn snapshot_api_sqlite() {
		let signals = DockerfileSignals {
			database: Some("sqlite".into()),
			..minimal_signals()
		};
		assert_eq!(
			generate(&signals).to_string(),
			include_str!("dockerfile_generator/snapshots/api_sqlite.dockerfile")
		);
	}

	// G5
	#[rstest]
	fn snapshot_api_grpc() {
		let signals = DockerfileSignals {
			grpc: true,
			..minimal_signals()
		};
		assert_eq!(
			generate(&signals).to_string(),
			include_str!("dockerfile_generator/snapshots/api_grpc.dockerfile")
		);
	}

	// G6
	#[rstest]
	fn snapshot_api_graphql() {
		let signals = DockerfileSignals {
			graphql: true,
			..minimal_signals()
		};
		assert_eq!(
			generate(&signals).to_string(),
			include_str!("dockerfile_generator/snapshots/api_graphql.dockerfile")
		);
	}

	// G7
	#[rstest]
	fn snapshot_api_full() {
		let signals = DockerfileSignals {
			database: Some("postgresql".into()),
			grpc: true,
			graphql: true,
			..minimal_signals()
		};
		assert_eq!(
			generate(&signals).to_string(),
			include_str!("dockerfile_generator/snapshots/api_full.dockerfile")
		);
	}

	// G8
	#[rstest]
	fn snapshot_pages_minimal() {
		let signals = DockerfileSignals {
			pages: true,
			wasm_bindgen_version: Some("0.2.100".into()),
			..minimal_signals()
		};
		assert_eq!(
			generate(&signals).to_string(),
			include_str!("dockerfile_generator/snapshots/pages_minimal.dockerfile")
		);
	}

	// G9
	#[rstest]
	fn snapshot_pages_postgres() {
		let signals = DockerfileSignals {
			pages: true,
			wasm_bindgen_version: Some("0.2.100".into()),
			database: Some("postgresql".into()),
			..minimal_signals()
		};
		assert_eq!(
			generate(&signals).to_string(),
			include_str!("dockerfile_generator/snapshots/pages_postgres.dockerfile")
		);
	}

	// G10
	#[rstest]
	fn snapshot_pages_full() {
		let signals = DockerfileSignals {
			pages: true,
			wasm_bindgen_version: Some("0.2.100".into()),
			database: Some("postgresql".into()),
			grpc: true,
			graphql: true,
			..minimal_signals()
		};
		assert_eq!(
			generate(&signals).to_string(),
			include_str!("dockerfile_generator/snapshots/pages_full.dockerfile")
		);
	}

	// G11
	#[rstest]
	fn snapshot_custom_base_image() {
		let signals = DockerfileSignals {
			base_image_override: Some("gcr.io/distroless/cc-debian12".into()),
			..minimal_signals()
		};
		let df = generate(&signals);
		let output = df.to_string();
		assert!(output.contains("FROM gcr.io/distroless/cc-debian12 AS runtime"));
		assert!(!output.contains("debian:bookworm-slim"));
		// Custom image: no Debian-specific commands
		assert!(!output.contains("apt-get"));
		assert!(!output.contains("useradd"));
		assert!(!output.contains("tini"));
	}

	// G12
	#[rstest]
	fn snapshot_cockroachdb_fallback() {
		let signals = DockerfileSignals {
			database: Some("cockroachdb".into()),
			..minimal_signals()
		};
		let df = generate(&signals);
		assert!(df.to_string().contains("libpq5"));
	}

	// SK1
	#[rstest]
	fn skip_when_custom_dockerfile_set() {
		// Arrange
		let dir = std::env::temp_dir();
		let mut config = ReinhardtCloudToml::default();
		config.source = Some(SourceSection {
			repository: String::new(),
			build: Some(BuildSection {
				dockerfile: Some("docker/Dockerfile.prod".to_string()),
				..Default::default()
			}),
			..Default::default()
		});

		// Act
		let result = should_skip_dockerfile(&dir, &config, false);

		// Assert
		assert_eq!(result, SkipReason::CustomDockerfile);
	}

	// SK2
	#[rstest]
	fn skip_when_exists_no_force() {
		// Arrange
		let dir = tempfile::tempdir().unwrap();
		std::fs::write(dir.path().join("Dockerfile"), "FROM scratch").unwrap();
		let config = ReinhardtCloudToml::default();

		// Act
		let result = should_skip_dockerfile(dir.path(), &config, false);

		// Assert
		assert_eq!(result, SkipReason::AlreadyExists);
	}

	// SK3
	#[rstest]
	fn no_skip_when_force() {
		// Arrange
		let dir = tempfile::tempdir().unwrap();
		std::fs::write(dir.path().join("Dockerfile"), "FROM scratch").unwrap();
		let config = ReinhardtCloudToml::default();

		// Act
		let result = should_skip_dockerfile(dir.path(), &config, true);

		// Assert
		assert_eq!(result, SkipReason::None);
	}

	// SK4
	#[rstest]
	fn no_skip_fresh_project() {
		// Arrange
		let dir = tempfile::tempdir().unwrap();
		let config = ReinhardtCloudToml::default();

		// Act
		let result = should_skip_dockerfile(dir.path(), &config, false);

		// Assert
		assert_eq!(result, SkipReason::None);
	}

	// SK5
	#[rstest]
	fn custom_dockerfile_empty_string() {
		// Arrange
		let dir = std::env::temp_dir();
		let mut config = ReinhardtCloudToml::default();
		config.source = Some(SourceSection {
			repository: String::new(),
			build: Some(BuildSection {
				dockerfile: Some(String::new()),
				..Default::default()
			}),
			..Default::default()
		});

		// Act
		let result = should_skip_dockerfile(&dir, &config, false);

		// Assert
		assert_eq!(result, SkipReason::None);
	}

	// SK6
	#[rstest]
	fn source_section_missing() {
		let dir = std::env::temp_dir();
		let config = ReinhardtCloudToml::default();
		assert_eq!(
			should_skip_dockerfile(&dir, &config, false),
			SkipReason::None
		);
	}

	// SK7a
	#[rstest]
	fn no_skip_when_default_dockerfile_path() {
		// Arrange
		let dir = std::env::temp_dir();
		let mut config = ReinhardtCloudToml::default();
		config.source = Some(SourceSection {
			repository: String::new(),
			build: Some(BuildSection {
				dockerfile: Some("Dockerfile".to_string()),
				..Default::default()
			}),
			..Default::default()
		});

		// Act
		let result = should_skip_dockerfile(&dir, &config, false);

		// Assert
		assert_eq!(result, SkipReason::None);
	}

	// SK7b
	#[rstest]
	fn no_skip_when_dot_slash_dockerfile_path() {
		// Arrange
		let dir = std::env::temp_dir();
		let mut config = ReinhardtCloudToml::default();
		config.source = Some(SourceSection {
			repository: String::new(),
			build: Some(BuildSection {
				dockerfile: Some("./Dockerfile".to_string()),
				..Default::default()
			}),
			..Default::default()
		});

		// Act
		let result = should_skip_dockerfile(&dir, &config, false);

		// Assert
		assert_eq!(result, SkipReason::None);
	}

	// SK8
	#[rstest]
	fn build_section_missing() {
		// Arrange
		let dir = std::env::temp_dir();
		let mut config = ReinhardtCloudToml::default();
		config.source = Some(SourceSection {
			repository: String::new(),
			build: None,
			..Default::default()
		});

		// Act
		let result = should_skip_dockerfile(&dir, &config, false);

		// Assert
		assert_eq!(result, SkipReason::None);
	}
}
