// reinhardt-migration-source: 1
// Generated by Reinhardt migrations.

use reinhardt::db::migrations::FieldType;
use reinhardt::db::migrations::prelude::*;
pub(super) fn migration() -> Migration {
	Migration::new("0002_accounts_users_last_login", "accounts")
		.add_operation(Operation::AddColumn {
			table: "accounts_users".to_string(),
			column: ColumnDefinition::new("last_login", FieldType::TimestampTz)
				.with_not_null(false)
				.with_unique(false)
				.with_primary_key(false)
				.with_auto_increment(false)
				.with_default(None)
				.with_generated(None)
				.with_domain_option(None),
			mysql_options: None,
		})
		.add_dependency("accounts", "0001_initial")
		.atomic(true)
		.with_initial(None)
		.state_only(false)
		.database_only(false)
}
