// reinhardt-migration-source: 1
// Generated by Reinhardt migrations.

use reinhardt::db::migrations::FieldType;
use reinhardt::db::migrations::prelude::*;
pub(super) fn migration() -> Migration {
	Migration::new("0003_accounts_social_accounts_nullable_access_expiry", "accounts")
	.add_operation(Operation::AlterColumn {
		table: "accounts_social_accounts".to_string(),
		column: "access_token_expires_at".to_string(),
		old_definition: Some(
			ColumnDefinition::new("access_token_expires_at", FieldType::TimestampTz)
				.with_not_null(true)
				.with_unique(false)
				.with_primary_key(false)
				.with_auto_increment(false)
				.with_default(None)
				.with_generated(None)
				.with_domain_option(None),
		),
		new_definition: ColumnDefinition::new("access_token_expires_at", FieldType::TimestampTz)
			.with_not_null(false)
			.with_unique(false)
			.with_primary_key(false)
			.with_auto_increment(false)
			.with_default(None)
			.with_generated(None)
			.with_domain_option(None),
		mysql_options: None,
	})
	// Workaround for kent8192/reinhardt-web#6724 (tracked in
	// kent8192/reinhardt-cloud#954): the forward SQL of `AlterColumn` on
	// PostgreSQL changes the type but never the column's nullability. Remove this
	// operation when the upstream issue is resolved.
	//
	// Ideal implementation (without workaround):
	//   the `AlterColumn` above alone emits
	//   `ALTER TABLE accounts_social_accounts ALTER COLUMN access_token_expires_at DROP NOT NULL;`
	.add_operation(Operation::RunSQL {
		sql: "ALTER TABLE accounts_social_accounts ALTER COLUMN access_token_expires_at DROP NOT NULL;"
			.to_string(),
		reverse_sql: Some(
			"ALTER TABLE accounts_social_accounts ALTER COLUMN access_token_expires_at SET NOT NULL;"
				.to_string(),
		),
	})
	.add_dependency("accounts", "0002_accounts_users_last_login")
	.atomic(true)
	.with_initial(None)
	.state_only(false)
	.database_only(false)
}
