// reinhardt-migration-source: 1
// Generated by Reinhardt migrations.

use reinhardt::db::migrations::FieldType;
use reinhardt::db::migrations::prelude::{
	ColumnDefinition, Constraint, ForeignKeyAction, Migration, Operation,
};
pub(super) fn migration() -> Migration {
	Migration::new("0001_initial", "secret")
		.add_operation(Operation::CreateTable {
			name: "cloud_secret_secretversion".to_string(),
			columns: vec![
				ColumnDefinition::new("ciphertext", FieldType::Text)
					.with_not_null(true)
					.with_unique(false)
					.with_primary_key(false)
					.with_auto_increment(false)
					.with_default(None)
					.with_generated(None)
					.with_domain_option(None),
				ColumnDefinition::new("created_at", FieldType::TimestampTz)
					.with_not_null(true)
					.with_unique(false)
					.with_primary_key(false)
					.with_auto_increment(false)
					.with_default(None)
					.with_generated(None)
					.with_domain_option(None),
				ColumnDefinition::new("environment_id", FieldType::Uuid)
					.with_not_null(true)
					.with_unique(false)
					.with_primary_key(false)
					.with_auto_increment(false)
					.with_default(None)
					.with_generated(None)
					.with_domain_option(None),
				ColumnDefinition::new("id", FieldType::Uuid)
					.with_not_null(true)
					.with_unique(false)
					.with_primary_key(true)
					.with_auto_increment(false)
					.with_default(None)
					.with_generated(None)
					.with_domain_option(None),
				ColumnDefinition::new("key_id", FieldType::VarChar(200u32))
					.with_not_null(true)
					.with_unique(false)
					.with_primary_key(false)
					.with_auto_increment(false)
					.with_default(None)
					.with_generated(None)
					.with_domain_option(None),
				ColumnDefinition::new("name", FieldType::VarChar(200u32))
					.with_not_null(true)
					.with_unique(false)
					.with_primary_key(false)
					.with_auto_increment(false)
					.with_default(None)
					.with_generated(None)
					.with_domain_option(None),
				ColumnDefinition::new("revoked", FieldType::Boolean)
					.with_not_null(true)
					.with_unique(false)
					.with_primary_key(false)
					.with_auto_increment(false)
					.with_default(Some("false".to_string()))
					.with_generated(None)
					.with_domain_option(None),
			],
			constraints: vec![Constraint::ForeignKey {
				name: "fk_cloud_secret_secretversion_environment_id".to_string(),
				columns: vec!["environment_id".to_string()],
				referenced_table: "cloud_environment".to_string(),
				referenced_columns: vec!["id".to_string()],
				on_delete: ForeignKeyAction::Restrict,
				on_update: ForeignKeyAction::NoAction,
				deferrable: None,
			}],
			without_rowid: None,
			interleave_in_parent: None,
			partition: None,
		})
		.add_operation(Operation::CreateIndex {
			table: "cloud_secret_secretversion".to_string(),
			columns: vec!["environment_id".to_string()],
			unique: false,
			index_type: None,
			where_clause: None,
			concurrently: false,
			expressions: None,
			mysql_options: None,
			operator_class: None,
		})
		.add_dependency("project", "0001_initial")
		.atomic(true)
		.with_initial(Some(true))
		.state_only(false)
		.database_only(false)
}
