// reinhardt-migration-source: 1
// Generated by Reinhardt migrations.

use reinhardt::db::migrations::FieldType;
use reinhardt::db::migrations::prelude::*;
pub(super) fn migration() -> Migration {
	Migration::new(
		"0002_github_repositories_import_claimed_at".to_string(),
		"github".to_string(),
	)
	.add_operation(Operation::AddColumn {
		table: "github_repositories".to_string(),
		column: ColumnDefinition::new("import_claimed_at".to_string(), FieldType::TimestampTz)
			.with_not_null(false)
			.with_unique(false)
			.with_primary_key(false)
			.with_auto_increment(false)
			.with_default(None)
			.with_generated(None)
			.with_domain_option(None),
		mysql_options: None,
	})
	.add_dependency("github".to_string(), "0001_initial".to_string())
	.atomic(true)
	.with_initial(None)
	.state_only(false)
	.database_only(false)
}
