// Generated by Reinhardt migrations.

use reinhardt::db::migrations::FieldType;
use reinhardt::db::migrations::prelude::*;
pub(super) fn migration() -> Migration {
	Migration {
		app_label: "github".to_string(),
		name: "0002_github_repositories_import_claimed_at".to_string(),
		operations: vec![Operation::AddColumn {
			table: "github_repositories".to_string(),
			column: ColumnDefinition {
				name: "import_claimed_at".to_string(),
				type_definition: FieldType::TimestampTz,
				not_null: false,
				unique: false,
				primary_key: false,
				auto_increment: false,
				default: None,
				generated: None,
				domain: None,
			},
			mysql_options: None,
		}],
		dependencies: vec![("github".to_string(), "0001_initial".to_string())],
		atomic: true,
		replaces: vec![],
		initial: None,
		state_only: false,
		database_only: false,
		swappable_dependencies: vec![],
		optional_dependencies: vec![],
	}
}
