// reinhardt-migration-source: 1
// Generated by Reinhardt migrations.

use reinhardt::db::migrations::FieldType;
use reinhardt::db::migrations::prelude::{ColumnDefinition, Constraint, ForeignKeyAction, Migration, Operation};
pub(super) fn migration() -> Migration {
	Migration::new(
		"0002_cloud_environment_grant_create_index_cloud__and_more",
		"organization",
	)
	.add_operation(Operation::CreateTable {
		name: "cloud_environment_grant".to_string(),
		columns: vec![
			ColumnDefinition::new("environment_id", FieldType::Uuid)
				.with_not_null(true)
				.with_unique(false)
				.with_primary_key(false)
				.with_auto_increment(false)
				.with_default(None)
				.with_generated(None)
				.with_domain_option(None),
			ColumnDefinition::new("id", FieldType::Uuid)
				.with_not_null(true)
				.with_unique(false)
				.with_primary_key(true)
				.with_auto_increment(false)
				.with_default(None)
				.with_generated(None)
				.with_domain_option(None),
			ColumnDefinition::new("organization_id", FieldType::Uuid)
				.with_not_null(true)
				.with_unique(false)
				.with_primary_key(false)
				.with_auto_increment(false)
				.with_default(None)
				.with_generated(None)
				.with_domain_option(None),
			ColumnDefinition::new("user_id", FieldType::Uuid)
				.with_not_null(true)
				.with_unique(false)
				.with_primary_key(false)
				.with_auto_increment(false)
				.with_default(None)
				.with_generated(None)
				.with_domain_option(None),
		],
		constraints: vec![
			Constraint::ForeignKey {
				name: "fk_cloud_environment_grant_organization_id".to_string(),
				columns: vec!["organization_id".to_string()],
				referenced_table: "cloud_organization_organization".to_string(),
				referenced_columns: vec!["id".to_string()],
				on_delete: ForeignKeyAction::Cascade,
				on_update: ForeignKeyAction::NoAction,
				deferrable: None,
			},
			Constraint::ForeignKey {
				name: "fk_cloud_environment_grant_user_id".to_string(),
				columns: vec!["user_id".to_string()],
				referenced_table: "cloud_identity_useraccount".to_string(),
				referenced_columns: vec!["id".to_string()],
				on_delete: ForeignKeyAction::Cascade,
				on_update: ForeignKeyAction::NoAction,
				deferrable: None,
			},
			Constraint::ForeignKey {
				name: "fk_cloud_environment_grant_environment_id".to_string(),
				columns: vec!["environment_id".to_string()],
				referenced_table: "cloud_environment".to_string(),
				referenced_columns: vec!["id".to_string()],
				on_delete: ForeignKeyAction::Cascade,
				on_update: ForeignKeyAction::NoAction,
				deferrable: None,
			},
			Constraint::Unique {
				name: "cloud_environment_grant_organization_id_user_id_environment_id_uniq"
					.to_string(),
				columns: vec![
					"organization_id".to_string(),
					"user_id".to_string(),
					"environment_id".to_string(),
				],
			},
		],
		without_rowid: None,
		interleave_in_parent: None,
		partition: None,
	})
	.add_operation(Operation::CreateIndex {
		table: "cloud_environment_grant".to_string(),
		columns: vec!["environment_id".to_string()],
		unique: false,
		index_type: None,
		where_clause: None,
		concurrently: false,
		expressions: None,
		mysql_options: None,
		operator_class: None,
	})
	.add_operation(Operation::CreateIndex {
		table: "cloud_environment_grant".to_string(),
		columns: vec!["organization_id".to_string()],
		unique: false,
		index_type: None,
		where_clause: None,
		concurrently: false,
		expressions: None,
		mysql_options: None,
		operator_class: None,
	})
	.add_operation(Operation::CreateIndex {
		table: "cloud_environment_grant".to_string(),
		columns: vec!["user_id".to_string()],
		unique: false,
		index_type: None,
		where_clause: None,
		concurrently: false,
		expressions: None,
		mysql_options: None,
		operator_class: None,
	})
	.add_dependency("organization", "0001_initial")
	.add_dependency("identity", "0001_initial")
	.add_dependency("project", "0002_cloud_environment_desired_runtime")
	.atomic(true)
	.with_initial(None)
	.state_only(false)
	.database_only(false)
}
