//! Generates `nuages.toml` content from project metadata.

use crate::feature_detector::ProjectMetadata;
use crate::settings_reader::DatabaseConfig;
use nuages_types::nuages_toml::{
	AppSection, AuthSection, CacheSection, DatabaseSection, NuagesToml, StorageSection,
	WorkerSection,
};

/// Generate a `NuagesToml` from project metadata and optional database config
pub(crate) fn generate_config(
	metadata: &ProjectMetadata,
	db_config: Option<&DatabaseConfig>,
) -> NuagesToml {
	let db_engine = db_config
		.map(|d| d.engine.clone())
		.or_else(|| metadata.signals.database.clone())
		.unwrap_or_else(|| "postgresql".to_owned());

	NuagesToml {
		app: AppSection {
			name: metadata.name.clone(),
			image: format!("{}:latest", metadata.name),
		},
		database: if metadata.signals.database.is_some() || db_config.is_some() {
			Some(DatabaseSection {
				engine: db_engine,
				..Default::default()
			})
		} else {
			None
		},
		auth: if metadata.signals.jwt {
			Some(AuthSection { jwt: true })
		} else {
			None
		},
		cache: metadata.signals.cache.as_ref().map(|backend| CacheSection {
			backend: backend.clone(),
			..Default::default()
		}),
		worker: if metadata.signals.background_worker {
			Some(WorkerSection::default())
		} else {
			None
		},
		storage: if metadata.signals.object_storage {
			Some(StorageSection::default())
		} else {
			None
		},
		..Default::default()
	}
}

/// Serialize `NuagesToml` to a TOML string with a header comment
pub(crate) fn generate_nuages_toml_string(config: &NuagesToml) -> String {
	let output = toml::to_string_pretty(config).unwrap_or_default();

	let header = "# nuages.toml — Generated by `nuages init`\n\
		# All values are inferred from the reinhardt-web project.\n\
		# Edit to customize deployment configuration.\n\n";

	format!("{header}{output}")
}

#[cfg(test)]
mod tests {
	use super::*;
	use crate::feature_detector::InfraSignals;
	use rstest::rstest;

	#[rstest]
	fn test_generate_config_with_database() {
		// Arrange
		let metadata = ProjectMetadata {
			name: "my-app".into(),
			version: "0.1.0".into(),
			features: vec!["db-postgres".into(), "auth-jwt".into()],
			signals: InfraSignals {
				database: Some("postgresql".into()),
				jwt: true,
				..Default::default()
			},
		};

		// Act
		let config = generate_config(&metadata, None);

		// Assert
		assert_eq!(config.app.name, "my-app");
		assert_eq!(config.app.image, "my-app:latest");
		assert_eq!(config.database.as_ref().unwrap().engine, "postgresql");
		assert!(config.auth.as_ref().unwrap().jwt);
		assert!(config.cache.is_none());
		assert!(config.worker.is_none());
	}

	#[rstest]
	fn test_generate_config_db_config_overrides_signal() {
		// Arrange
		let metadata = ProjectMetadata {
			name: "app".into(),
			version: "0.1.0".into(),
			features: vec!["db-postgres".into()],
			signals: InfraSignals {
				database: Some("postgresql".into()),
				..Default::default()
			},
		};
		let db_config = DatabaseConfig {
			engine: "mysql".into(),
			host: "db.local".into(),
			port: 3306,
			name: "mydb".into(),
		};

		// Act
		let config = generate_config(&metadata, Some(&db_config));

		// Assert
		assert_eq!(config.database.as_ref().unwrap().engine, "mysql");
	}

	#[rstest]
	fn test_generate_config_minimal_no_infra() {
		// Arrange
		let metadata = ProjectMetadata {
			name: "bare".into(),
			version: "0.1.0".into(),
			features: vec!["core".into()],
			signals: InfraSignals::default(),
		};

		// Act
		let config = generate_config(&metadata, None);

		// Assert
		assert_eq!(config.app.name, "bare");
		assert!(config.database.is_none());
		assert!(config.auth.is_none());
		assert!(config.cache.is_none());
		assert!(config.worker.is_none());
		assert!(config.storage.is_none());
	}

	#[rstest]
	fn test_generate_config_with_cache_and_worker() {
		// Arrange
		let metadata = ProjectMetadata {
			name: "full".into(),
			version: "0.1.0".into(),
			features: vec!["redis-backend".into(), "tasks".into()],
			signals: InfraSignals {
				cache: Some("redis".into()),
				background_worker: true,
				..Default::default()
			},
		};

		// Act
		let config = generate_config(&metadata, None);

		// Assert
		assert_eq!(config.cache.as_ref().unwrap().backend, "redis");
		assert!(config.worker.is_some());
	}

	#[rstest]
	fn test_generate_config_with_storage() {
		// Arrange
		let metadata = ProjectMetadata {
			name: "storage-app".into(),
			version: "0.1.0".into(),
			features: vec!["storage".into()],
			signals: InfraSignals {
				object_storage: true,
				..Default::default()
			},
		};

		// Act
		let config = generate_config(&metadata, None);

		// Assert
		assert!(config.storage.is_some());
	}

	#[rstest]
	fn test_generate_nuages_toml_string_has_header() {
		// Arrange
		let config = NuagesToml {
			app: AppSection {
				name: "test".into(),
				image: "test:latest".into(),
			},
			..Default::default()
		};

		// Act
		let output = generate_nuages_toml_string(&config);

		// Assert
		assert!(output.starts_with("# nuages.toml"));
		assert!(output.contains("nuages init"));
		assert!(output.contains("[app]"));
		assert!(output.contains("name = \"test\""));
	}

	#[rstest]
	fn test_generate_nuages_toml_string_roundtrip() {
		// Arrange
		let config = NuagesToml {
			app: AppSection {
				name: "rt".into(),
				image: "rt:v1".into(),
			},
			database: Some(DatabaseSection {
				engine: "postgresql".into(),
				..Default::default()
			}),
			auth: Some(AuthSection { jwt: true }),
			..Default::default()
		};

		// Act
		let output = generate_nuages_toml_string(&config);
		// Strip header comments for parsing
		let toml_body: String = output
			.lines()
			.filter(|l| !l.starts_with('#'))
			.collect::<Vec<_>>()
			.join("\n");
		let parsed: NuagesToml = toml::from_str(&toml_body).unwrap();

		// Assert
		assert_eq!(parsed.app.name, "rt");
		assert_eq!(parsed.database.unwrap().engine, "postgresql");
		assert!(parsed.auth.unwrap().jwt);
	}
}
