//! Reinhardt Cloud Dashboard and Control Plane.
//!
//! Eight Apps own domain policy and persistence. The Dashboard uses Pages
//! on native and browser targets, with styling generated by `style!`.
//!
//! Password sessions and organization-scoped project reads are connected.
//! Read-only Pages show Environment inputs
//! and their latest operation without treating desired state as observed readiness.
//! Planned integration includes OIDC, authenticated project mutations, GitHub
//! connections, Agent delivery transports, secret delivery, and live logs.

#[cfg(server)]
pub use reinhardt::core::async_trait;
#[cfg(server)]
pub use reinhardt::reinhardt_di::params;
#[cfg(server)]
pub use reinhardt::{reinhardt_apps, reinhardt_core, reinhardt_http};

pub mod apps;
pub mod client;
pub mod config;

#[cfg(server)]
pub use config::settings::get_settings;
#[cfg(server)]
pub use config::urls::routes;
