// Composite UNIQUE constraint enforcing per-organization cluster name
// uniqueness (mirrors the model-level `unique_together = ("organization_id",
// "name")` declaration in `apps::clusters::models::Cluster`).
//
// Regenerated from `cargo run --bin manage -- makemigrations clusters` once
// reinhardt-web#4041 (closes reinhardt-web#4040) propagated the
// `added_constraints` loop into `MigrationAutodetector::generate_migrations()`.
// The diagnostic test `apps::clusters::tests::unit::test_cluster_model::tests::
// diag_makemigrations_path_emits_add_constraint` proves the CLI path now
// emits AddConstraint correctly.
//
// Workaround for kent8192/reinhardt-web#4052 (tracked in reinhardt-cloud#476).
// Remove this workaround when the upstream issue is resolved.
//
// History: reinhardt-web#4049 (the synthetic-clone variant, originally
// tracked as reinhardt-cloud#475) was closed by reinhardt-web#4050. That fix
// resolves the symmetric `from`/`to` `FieldState` case but does NOT cover
// the production CLI path where `from_state` is built via
// `ProjectState::apply_migration_operations` from a `CreateTable` op and
// the model overrides `table_name = "clusters"` to match `0001_initial`'s
// table. The autodetector still emits a no-op
// `Operation::AlterColumn { old_definition: None, .. }` for the unchanged
// `id` primary key in that scenario. The `#[ignore]`-marked regression
// `apps::clusters::tests::unit::test_cluster_model::tests::
// diag_apply_migration_operations_from_state_no_spurious_altercolumn`
// pins the residual bug.
//
// The autogenerated output therefore still includes a spurious
// `Operation::AlterColumn` for `id`. That AlterColumn has been hand-removed;
// only the semantically meaningful AddConstraint operation is retained.
//
// Ideal implementation (without workaround): the entire body below would be
// the unedited output of `cargo run --bin manage -- makemigrations clusters`,
// containing only the AddConstraint operation.

use reinhardt::db::migrations::prelude::*;
pub fn migration() -> Migration {
	Migration {
		app_label: "clusters".to_string(),
		name: "0005_add_organization_id_name_unique".to_string(),
		operations: vec![Operation::AddConstraint {
			table: "clusters".to_string(),
			constraint_sql:
				"CONSTRAINT clusters_organization_id_name_uniq UNIQUE (organization_id, name)"
					.to_string(),
		}],
		dependencies: vec![(
			"clusters".to_string(),
			"0004_replace_user_id_with_organization_id".to_string(),
		)],
		atomic: true,
		replaces: vec![],
		initial: None,
		state_only: false,
		database_only: false,
		swappable_dependencies: vec![],
		optional_dependencies: vec![],
	}
}
