//! URL configuration for the dashboard app.
//!
//! Declares the project-level SPA `home` route reachable from the
//! top-level navigation. Server-side reverse URL resolution and SPA
//! navigation both go through the typed accessor
//! `urls.client().dashboard().home()` generated by `#[url_patterns]`.
//! Per-section routes (`clusters:list`, `deployments:list`) are owned by
//! their respective apps' `url_patterns`.

pub mod ws_urls;

use reinhardt::url_patterns;
use reinhardt::urls::prelude::UnifiedRouter;

use crate::apps::dashboard::client::layout::dashboard_shell;
use crate::config::apps::InstalledApp;

/// Returns the unified URL patterns for the dashboard app.
#[url_patterns(InstalledApp::dashboard, mode = unified)]
pub fn url_patterns() -> UnifiedRouter {
	UnifiedRouter::new()
		.server(|s| s)
		.client(|c| c.named_route("home", "/", dashboard_shell))
}
