//! URL configuration for the dashboard app.
//!
//! Declares the project-level SPA routes (`home`, `clusters`,
//! `deployments`) reachable from the top-level navigation. Server-side
//! reverse URL resolution and SPA navigation both go through the typed
//! accessor `urls.client().dashboard().<route>()` generated by
//! `#[url_patterns]`.

pub mod ws_urls;

use reinhardt::ClientUrlResolver;
use reinhardt::url_patterns;
use reinhardt::urls::prelude::UnifiedRouter;

use crate::apps::dashboard::views::{dashboard_shell, not_found_page};
use crate::config::apps::InstalledApp;

/// Returns the unified URL patterns for the dashboard app.
///
/// `clusters` and `deployments` currently render the 404 placeholder
/// until their dedicated pages are implemented; the named routes still
/// resolve so navigation hrefs do not break.
#[url_patterns(InstalledApp::dashboard, mode = unified)]
pub fn url_patterns() -> UnifiedRouter {
	UnifiedRouter::new().server(|s| s).client(|c| {
		c.named_route("home", "/", dashboard_shell)
			.named_route("clusters", "/clusters", not_found_page)
			.named_route("deployments", "/deployments", not_found_page)
	})
}
