platform: onpremise

image:
  repository: registry.internal/nuages/nuages-operator
  pullPolicy: Always

imagePullSecrets:
  - name: internal-registry-secret

tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"
