// reinhardt-migration-source: 1
// Generated by Reinhardt migrations.

use reinhardt::db::migrations::FieldType;
use reinhardt::db::migrations::prelude::{
	ColumnDefinition, Constraint, ForeignKeyAction, Migration, Operation,
};
pub(super) fn migration() -> Migration {
	Migration::new("0001_initial", "source")
		.add_operation(Operation::CreateTable {
			name: "cloud_source_repositoryconnection".to_string(),
			columns: vec![
				ColumnDefinition::new("created_at", FieldType::TimestampTz)
					.with_not_null(true)
					.with_unique(false)
					.with_primary_key(false)
					.with_auto_increment(false)
					.with_default(None)
					.with_generated(None)
					.with_domain_option(None),
				ColumnDefinition::new("github_installation_id", FieldType::BigInteger)
					.with_not_null(true)
					.with_unique(false)
					.with_primary_key(false)
					.with_auto_increment(false)
					.with_default(None)
					.with_generated(None)
					.with_domain_option(None),
				ColumnDefinition::new("id", FieldType::Uuid)
					.with_not_null(true)
					.with_unique(false)
					.with_primary_key(true)
					.with_auto_increment(false)
					.with_default(None)
					.with_generated(None)
					.with_domain_option(None),
				ColumnDefinition::new("organization_id", FieldType::Uuid)
					.with_not_null(true)
					.with_unique(false)
					.with_primary_key(false)
					.with_auto_increment(false)
					.with_default(None)
					.with_generated(None)
					.with_domain_option(None),
			],
			constraints: vec![Constraint::ForeignKey {
				name: "fk_cloud_source_repositoryconnection_organization_id".to_string(),
				columns: vec!["organization_id".to_string()],
				referenced_table: "cloud_organization_organization".to_string(),
				referenced_columns: vec!["id".to_string()],
				on_delete: ForeignKeyAction::Cascade,
				on_update: ForeignKeyAction::NoAction,
				deferrable: None,
			}],
			without_rowid: None,
			interleave_in_parent: None,
			partition: None,
		})
		.add_operation(Operation::CreateIndex {
			table: "cloud_source_repositoryconnection".to_string(),
			columns: vec!["organization_id".to_string()],
			unique: false,
			index_type: None,
			where_clause: None,
			concurrently: false,
			expressions: None,
			mysql_options: None,
			operator_class: None,
		})
		.add_dependency("organization", "0001_initial")
		.atomic(true)
		.with_initial(Some(true))
		.state_only(false)
		.database_only(false)
}
