// reinhardt-migration-source: 1
// Generated by Reinhardt migrations.

use reinhardt::db::migrations::FieldType;
use reinhardt::db::migrations::prelude::{ColumnDefinition, Migration, Operation};
pub(super) fn migration() -> Migration {
	Migration::new("0002_cloud_environment_desired_runtime", "project")
		.add_operation(Operation::AddColumn {
			table: "cloud_environment".to_string(),
			column: ColumnDefinition::new("desired_runtime", FieldType::Text)
				.with_not_null(true)
				.with_unique(false)
				.with_primary_key(false)
				.with_auto_increment(false)
				.with_default(Some("'{}'".to_string()))
				.with_generated(None)
				.with_domain_option(None),
			mysql_options: None,
		})
		.add_dependency("project", "0001_initial")
		.atomic(true)
		.with_initial(None)
		.state_only(false)
		.database_only(false)
}
