{{- if .Values.logging.loki.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "reinhardt-cloud-operator.fullname" . }}-promtail
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "reinhardt-cloud-operator.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "reinhardt-cloud-operator.name" . }}-promtail
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "reinhardt-cloud-operator.name" . }}-promtail
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ include "reinhardt-cloud-operator.fullname" . }}-promtail
      securityContext:
        {{- toYaml .Values.logging.loki.podSecurityContext | nindent 8 }}
      tolerations:
        - effect: NoSchedule
          operator: Exists
      containers:
        - name: promtail
          image: {{ .Values.logging.loki.promtailImage }}
          args:
            - "-config.file=/etc/promtail/promtail.yaml"
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: config
              mountPath: /etc/promtail
            - name: run
              mountPath: /run/promtail
            - name: pods
              mountPath: /var/log/pods
              readOnly: true
          resources:
            {{- toYaml .Values.logging.loki.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "reinhardt-cloud-operator.fullname" . }}-promtail
        - name: run
          emptyDir: {}
        - name: pods
          hostPath:
            path: /var/log/pods
{{- end }}
