{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "reinhardt-cloud-operator.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "reinhardt-cloud-operator.labels" . | nindent 4 }}
  {{- with .Values.metrics.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.metrics.service.type }}
  ports:
    - name: metrics
      port: {{ .Values.metrics.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "reinhardt-cloud-operator.selectorLabels" . | nindent 4 }}
{{- end }}
