// reinhardt-migration-source: 1
// Generated by Reinhardt migrations.

use reinhardt::db::migrations::FieldType;
use reinhardt::db::migrations::prelude::{
	ColumnDefinition, Constraint, ForeignKeyAction, Migration, Operation,
};
pub(super) fn migration() -> Migration {
	Migration::new("0001_initial", "deployment")
		.add_operation(Operation::CreateTable {
			name: "cloud_deployment_operation".to_string(),
			columns: vec![
				ColumnDefinition::new("created_at", FieldType::TimestampTz)
					.with_not_null(true)
					.with_unique(false)
					.with_primary_key(false)
					.with_auto_increment(false)
					.with_default(None)
					.with_generated(None)
					.with_domain_option(None),
				ColumnDefinition::new("environment_id", FieldType::Uuid)
					.with_not_null(true)
					.with_unique(false)
					.with_primary_key(false)
					.with_auto_increment(false)
					.with_default(None)
					.with_generated(None)
					.with_domain_option(None),
				ColumnDefinition::new("environment_version", FieldType::BigInteger)
					.with_not_null(true)
					.with_unique(false)
					.with_primary_key(false)
					.with_auto_increment(false)
					.with_default(None)
					.with_generated(None)
					.with_domain_option(None),
				ColumnDefinition::new("id", FieldType::Uuid)
					.with_not_null(true)
					.with_unique(false)
					.with_primary_key(true)
					.with_auto_increment(false)
					.with_default(None)
					.with_generated(None)
					.with_domain_option(None),
				ColumnDefinition::new("idempotency_key", FieldType::VarChar(200u32))
					.with_not_null(true)
					.with_unique(false)
					.with_primary_key(false)
					.with_auto_increment(false)
					.with_default(None)
					.with_generated(None)
					.with_domain_option(None),
				ColumnDefinition::new("kind", FieldType::VarChar(32u32))
					.with_not_null(true)
					.with_unique(false)
					.with_primary_key(false)
					.with_auto_increment(false)
					.with_default(None)
					.with_generated(None)
					.with_domain_option(None),
				ColumnDefinition::new("organization_id", FieldType::Uuid)
					.with_not_null(true)
					.with_unique(false)
					.with_primary_key(false)
					.with_auto_increment(false)
					.with_default(None)
					.with_generated(None)
					.with_domain_option(None),
				ColumnDefinition::new("state", FieldType::VarChar(32u32))
					.with_not_null(true)
					.with_unique(false)
					.with_primary_key(false)
					.with_auto_increment(false)
					.with_default(None)
					.with_generated(None)
					.with_domain_option(None),
			],
			constraints: vec![
                Constraint::ForeignKey { name :
                "fk_cloud_deployment_operation_organization_id".to_string(), columns :
                vec!["organization_id".to_string()], referenced_table :
                "cloud_organization_organization".to_string(), referenced_columns :
                vec!["id".to_string()], on_delete : ForeignKeyAction::Restrict, on_update
                : ForeignKeyAction::NoAction, deferrable : None, },
                Constraint::ForeignKey { name :
                "fk_cloud_deployment_operation_environment_id".to_string(), columns :
                vec!["environment_id".to_string()], referenced_table :
                "cloud_environment".to_string(), referenced_columns : vec!["id"
                .to_string()], on_delete : ForeignKeyAction::Restrict, on_update :
                ForeignKeyAction::NoAction, deferrable : None, }, Constraint::Unique {
                name :
                "cloud_deployment_operation_organization_id_environment_id_idempotency_key_uniq"
                .to_string(), columns : vec!["organization_id".to_string(),
                "environment_id".to_string(), "idempotency_key".to_string()], }
            ],
			without_rowid: None,
			interleave_in_parent: None,
			partition: None,
		})
		.add_operation(Operation::CreateIndex {
			table: "cloud_deployment_operation".to_string(),
			columns: vec!["environment_id".to_string()],
			unique: false,
			index_type: None,
			where_clause: None,
			concurrently: false,
			expressions: None,
			mysql_options: None,
			operator_class: None,
		})
		.add_operation(Operation::CreateIndex {
			table: "cloud_deployment_operation".to_string(),
			columns: vec!["organization_id".to_string()],
			unique: false,
			index_type: None,
			where_clause: None,
			concurrently: false,
			expressions: None,
			mysql_options: None,
			operator_class: None,
		})
		.add_operation(Operation::CreateTable {
			name: "cloud_dispatch_record".to_string(),
			columns: vec![
				ColumnDefinition::new("delivered", FieldType::Boolean)
					.with_not_null(true)
					.with_unique(false)
					.with_primary_key(false)
					.with_auto_increment(false)
					.with_default(Some("false".to_string()))
					.with_generated(None)
					.with_domain_option(None),
				ColumnDefinition::new("environment_id", FieldType::Uuid)
					.with_not_null(true)
					.with_unique(false)
					.with_primary_key(false)
					.with_auto_increment(false)
					.with_default(None)
					.with_generated(None)
					.with_domain_option(None),
				ColumnDefinition::new("environment_version", FieldType::BigInteger)
					.with_not_null(true)
					.with_unique(false)
					.with_primary_key(false)
					.with_auto_increment(false)
					.with_default(None)
					.with_generated(None)
					.with_domain_option(None),
				ColumnDefinition::new("id", FieldType::Uuid)
					.with_not_null(true)
					.with_unique(false)
					.with_primary_key(true)
					.with_auto_increment(false)
					.with_default(None)
					.with_generated(None)
					.with_domain_option(None),
				ColumnDefinition::new("operation_id", FieldType::Uuid)
					.with_not_null(true)
					.with_unique(false)
					.with_primary_key(false)
					.with_auto_increment(false)
					.with_default(None)
					.with_generated(None)
					.with_domain_option(None),
				ColumnDefinition::new("payload", FieldType::VarChar(65535u32))
					.with_not_null(true)
					.with_unique(false)
					.with_primary_key(false)
					.with_auto_increment(false)
					.with_default(None)
					.with_generated(None)
					.with_domain_option(None),
			],
			constraints: vec![
				Constraint::ForeignKey {
					name: "fk_cloud_dispatch_record_environment_id".to_string(),
					columns: vec!["environment_id".to_string()],
					referenced_table: "cloud_environment".to_string(),
					referenced_columns: vec!["id".to_string()],
					on_delete: ForeignKeyAction::Restrict,
					on_update: ForeignKeyAction::NoAction,
					deferrable: None,
				},
				Constraint::ForeignKey {
					name: "fk_cloud_dispatch_record_operation_id".to_string(),
					columns: vec!["operation_id".to_string()],
					referenced_table: "cloud_deployment_operation".to_string(),
					referenced_columns: vec!["id".to_string()],
					on_delete: ForeignKeyAction::Cascade,
					on_update: ForeignKeyAction::NoAction,
					deferrable: None,
				},
				Constraint::Unique {
					name: "cloud_dispatch_record_operation_id_uniq_f0b35676".to_string(),
					columns: vec!["operation_id".to_string()],
				},
			],
			without_rowid: None,
			interleave_in_parent: None,
			partition: None,
		})
		.add_operation(Operation::CreateIndex {
			table: "cloud_dispatch_record".to_string(),
			columns: vec!["environment_id".to_string()],
			unique: false,
			index_type: None,
			where_clause: None,
			concurrently: false,
			expressions: None,
			mysql_options: None,
			operator_class: None,
		})
		.add_dependency("organization", "0001_initial")
		.add_dependency("project", "0001_initial")
		.atomic(true)
		.with_initial(Some(true))
		.state_only(false)
		.database_only(false)
}
