// reinhardt-migration-source: 1
// Generated by Reinhardt migrations.

use reinhardt::db::migrations::FieldType;
use reinhardt::db::migrations::prelude::{ColumnDefinition, Migration, Operation};
pub(super) fn migration() -> Migration {
	Migration::new(
            "0002_cloud_dispatch_record_cluster_id_cloud_depl_and_more",
            "deployment",
        )
        .add_operation(Operation::AddColumn {
            table: "cloud_dispatch_record".to_string(),
            column: ColumnDefinition::new("cluster_id", FieldType::Uuid)
                .with_not_null(true)
                .with_unique(false)
                .with_primary_key(false)
                .with_auto_increment(false)
                .with_default(None)
                .with_generated(None)
                .with_domain_option(None),
            mysql_options: None,
        })
        .add_operation(Operation::AddColumn {
            table: "cloud_deployment_operation".to_string(),
            column: ColumnDefinition::new(
                    "request_fingerprint",
                    FieldType::VarChar(64u32),
                )
                .with_not_null(true)
                .with_unique(false)
                .with_primary_key(false)
                .with_auto_increment(false)
                .with_default(Some("''".to_string()))
                .with_generated(None)
                .with_domain_option(None),
            mysql_options: None,
        })
        .add_operation(Operation::AddConstraint {
            table: "cloud_dispatch_record".to_string(),
            constraint_sql: "CONSTRAINT fk_cloud_dispatch_record_cluster_id FOREIGN KEY (cluster_id) REFERENCES cloud_cluster_cluster(id) ON DELETE RESTRICT ON UPDATE NO ACTION"
                .to_string(),
        })
        .add_operation(Operation::CreateIndex {
            table: "cloud_dispatch_record".to_string(),
            columns: vec!["cluster_id".to_string()],
            unique: false,
            index_type: None,
            where_clause: None,
            concurrently: false,
            expressions: None,
            mysql_options: None,
            operator_class: None,
        })
        .add_dependency("deployment", "0001_initial")
        .add_dependency(
            "cluster",
            "0002_cloud_environment_allocation_create_index_c_and_more",
        )
        .atomic(true)
        .with_initial(None)
        .state_only(false)
        .database_only(false)
}
