//! `GET /oauth/{provider}/start/` — kick off the OAuth authorization flow.
//!
//! Builds the provider's authorization URL via `SocialAuthBackend::begin_auth`
//! (which generates a fresh `state`, persists it with PKCE verifier in the
//! state store, and returns the URL to redirect the browser to). Replies
//! with a `302 Found` to that URL.
//!
//! `provider` is rejected as 404 when not enabled in `OAuthSettings`,
//! preventing requests for `/oauth/twitter/start/` etc. from reaching the
//! framework's provider registry where they would surface as a 500.

use reinhardt::core::exception::Error as AppError;
use reinhardt::http::ViewResult;
use reinhardt::{Path, Response, StatusCode, get};
use tracing::error;

use crate::apps::auth::services::oauth::backend::build_social_auth_backend;
use crate::apps::auth::services::oauth::config::OAuthSettings;

#[get("/oauth/{provider}/start/", name = "oauth_start")]
pub async fn oauth_start(Path(provider): Path<String>) -> ViewResult<Response> {
	let settings = OAuthSettings::from_env();
	if settings.get(&provider).is_none() {
		return Err(AppError::NotFound(format!(
			"OAuth provider not enabled: {provider}"
		)));
	}

	let backend = build_social_auth_backend(&settings)
		.await
		.map_err(|e| {
			error!("OAuth backend init failed: {e}");
			AppError::Internal("OAuth not available".to_string())
		})?
		.ok_or_else(|| AppError::NotFound("OAuth not configured".to_string()))?;

	// `begin_auth` with `None`/`None` lets reinhardt-auth generate a fresh
	// state (cryptographically random) and a PKCE verifier internally. The
	// verifier is persisted into the state store keyed by state and is
	// transparently consumed by `handle_callback`.
	let result = backend.begin_auth(&provider, None, None).await.map_err(|e| {
		error!("begin_auth({provider}) failed: {e}");
		AppError::Internal("OAuth start failed".to_string())
	})?;

	Ok(Response::new(StatusCode::FOUND).with_header("Location", &result.authorization_url))
}

#[cfg(test)]
mod tests {
	//! Inline unit tests for `oauth_start`.
	//!
	//! The `_original` function generated by `#[get(...)]` is module-private,
	//! so view-level unit tests must live in the same source file as the
	//! view itself. These cover the easily-reachable error and happy paths
	//! without standing up the HTTP harness:
	//!
	//!   * provider-not-enabled → 404 (`AppError::NotFound`)
	//!   * provider configured  → 302 with a `Location` header pointing at
	//!     the provider's authorization endpoint (PKCE/state generated
	//!     locally; no network required because `begin_auth` is in-process
	//!     for OAuth2)

	use super::*;
	use rstest::rstest;
	use serial_test::serial;

	const KEY_ID: &str = "REINHARDT_CLOUD_OAUTH_GITHUB_CLIENT_ID";
	const KEY_SECRET: &str = "REINHARDT_CLOUD_OAUTH_GITHUB_CLIENT_SECRET";
	const KEY_REDIRECT: &str = "REINHARDT_CLOUD_OAUTH_GITHUB_REDIRECT_URI";

	/// RAII guard that restores OAuth env vars on drop. Mirrors the pattern
	/// used by `test_oauth_settings.rs` so concurrent serial groups behave
	/// the same way.
	struct EnvGuard {
		saved: Vec<(String, Option<String>)>,
	}

	impl EnvGuard {
		fn set(vars: Vec<(&str, Option<&str>)>) -> Self {
			let mut saved = Vec::new();
			for (key, new_val) in &vars {
				saved.push((key.to_string(), std::env::var(key).ok()));
				// SAFETY: called in a serial test before any parallel tasks read these vars.
				unsafe {
					match new_val {
						Some(v) => std::env::set_var(key, v),
						None => std::env::remove_var(key),
					}
				}
			}
			Self { saved }
		}
	}

	impl Drop for EnvGuard {
		fn drop(&mut self) {
			for (key, old_val) in &self.saved {
				// SAFETY: restoring env vars in serial test teardown.
				unsafe {
					match old_val {
						Some(v) => std::env::set_var(key, v),
						None => std::env::remove_var(key),
					}
				}
			}
		}
	}

	#[rstest]
	#[serial(env_oauth)]
	#[tokio::test]
	async fn test_oauth_start_returns_404_when_provider_not_enabled() {
		// Arrange — no GitHub credentials in env, so `OAuthSettings::get`
		// returns None for every provider id.
		let _g = EnvGuard::set(vec![(KEY_ID, None), (KEY_SECRET, None), (KEY_REDIRECT, None)]);

		// Act
		let result = oauth_start_original(Path("github".to_string())).await;

		// Assert
		match result {
			Err(AppError::NotFound(msg)) => {
				assert_eq!(msg, "OAuth provider not enabled: github");
			}
			other => panic!("expected NotFound, got {other:?}"),
		}
	}

	#[rstest]
	#[serial(env_oauth)]
	#[tokio::test]
	async fn test_oauth_start_returns_404_for_unknown_provider() {
		// Arrange — even with GitHub credentials present, an unknown
		// provider id (e.g. "twitter") must still 404 rather than reaching
		// the framework registry where it would surface as 500.
		let _g = EnvGuard::set(vec![
			(KEY_ID, Some("test-id")),
			(KEY_SECRET, Some("test-secret")),
			(KEY_REDIRECT, Some("https://example.test/cb")),
		]);

		// Act
		let result = oauth_start_original(Path("twitter".to_string())).await;

		// Assert
		match result {
			Err(AppError::NotFound(msg)) => {
				assert_eq!(msg, "OAuth provider not enabled: twitter");
			}
			other => panic!("expected NotFound, got {other:?}"),
		}
	}

	#[rstest]
	#[serial(env_oauth)]
	#[tokio::test]
	async fn test_oauth_start_redirects_to_provider_when_configured() {
		// Arrange — full GitHub credentials so OAuthSettings reports the
		// provider as enabled and `build_social_auth_backend` returns Some.
		let _g = EnvGuard::set(vec![
			(KEY_ID, Some("test-client-id")),
			(KEY_SECRET, Some("test-client-secret")),
			(KEY_REDIRECT, Some("https://example.test/cb")),
		]);

		// Act
		let response = oauth_start_original(Path("github".to_string()))
			.await
			.expect("start should succeed when provider is configured");

		// Assert — 302 with a Location header that includes the canonical
		// github.com authorize endpoint and the configured client_id. The
		// exact `state` and PKCE challenge are random per call, so we
		// only assert on the stable parts of the URL.
		assert_eq!(response.status, StatusCode::FOUND);
		let location = response
			.headers
			.get("Location")
			.and_then(|v| v.to_str().ok())
			.expect("Location header must be present on 302");
		assert!(
			location.contains("github.com"),
			"authorization URL should target github.com: {location}"
		);
		assert!(
			location.contains("client_id=test-client-id"),
			"authorization URL should embed configured client_id: {location}"
		);
		assert!(
			location.contains("state="),
			"authorization URL should include CSRF state: {location}"
		);
	}
}
