//! `POST /oauth/{provider}/unlink/` — remove the link to a social provider.
//!
//! Authentication is required (caller must already be logged in via session
//! cookie or JWT). Lockout protection: if the user has no usable password
//! AND this is their last social link, the request is rejected with 422 so
//! the user cannot accidentally make their account unreachable.

use reinhardt::core::exception::Error as AppError;
use reinhardt::core::serde::json;
use reinhardt::db::orm::{FilterOperator, FilterValue, Model};
use reinhardt::http::ViewResult;
use reinhardt::{AuthInfo, Path, Response, StatusCode, post};
use reinhardt_auth::social::storage::SocialAccountStorage;
use tracing::error;
use uuid::Uuid;

use crate::apps::auth::models::User;
use crate::apps::auth::services::oauth::storage::OrmSocialAccountStorage;

#[post("/oauth/{provider}/unlink/", name = "oauth_unlink")]
pub async fn oauth_unlink(
	Path(provider): Path<String>,
	#[inject] AuthInfo(state): AuthInfo,
) -> ViewResult<Response> {
	let user_id = Uuid::parse_str(state.user_id())
		.map_err(|e| AppError::Authentication(format!("invalid user_id in token: {e}")))?;

	let user = User::objects()
		.filter(
			User::field_id(),
			FilterOperator::Eq,
			FilterValue::String(user_id.to_string()),
		)
		.first()
		.await
		.map_err(|e| {
			error!("user lookup failed during unlink: {e}");
			AppError::Internal("user lookup failed".to_string())
		})?
		.ok_or_else(|| AppError::NotFound("user not found".to_string()))?;

	let storage = OrmSocialAccountStorage::new();
	let links = storage.find_by_user(user_id).await.map_err(|e| {
		error!("storage list failed during unlink: {e}");
		AppError::Internal("storage list failed".to_string())
	})?;

	let target = links
		.iter()
		.find(|l| l.provider == provider)
		.ok_or_else(|| AppError::NotFound(format!("no link to provider: {provider}")))?;

	// Lockout protection: if the user has no usable password AND this is
	// their only social link, deleting it would lock them out of the
	// account. Refuse with a 422 so the client can prompt them to set a
	// password first.
	if user.password_hash.is_none() && links.len() == 1 {
		return Err(AppError::Validation(
			"cannot unlink the last sign-in method; set a password before unlinking"
				.to_string(),
		));
	}

	storage.delete(target.id).await.map_err(|e| {
		error!("storage delete failed during unlink: {e}");
		AppError::Internal("storage delete failed".to_string())
	})?;

	let body = json::to_vec(&serde_json::json!({"success": true, "provider": provider}))?;
	Ok(Response::new(StatusCode::OK)
		.with_header("Content-Type", "application/json")
		.with_body(body))
}

#[cfg(test)]
mod tests {
	//! Inline tests for `oauth_unlink`.
	//!
	//! The `_original` function generated by `#[post(...)]` is module-
	//! private, so view-level tests must live in the same source file as
	//! the view itself.
	//!
	//! Coverage map:
	//!   * malformed user_id  → 401 (`AppError::Authentication`) — no DB
	//!   * user-not-found     → 404 — DB
	//!   * no-link-to-provider → 404 — DB
	//!   * lockout protection  → 422 (`AppError::Validation`) — DB
	//!   * happy path          → 200 JSON — DB
	//!
	//! The DB-backed cases reuse the `postgres_with_migrations_from_dir`
	//! fixture used elsewhere in the auth integration suite.
	#![allow(clippy::too_many_lines)]

	use std::sync::Arc;

	use super::*;
	use chrono::Duration;
	use reinhardt::BaseUser;
	use reinhardt::core::exception::Error as AppError;
	use reinhardt::http::AuthState;
	use reinhardt::prelude::DatabaseConnection;
	use reinhardt::test::APIClient;
	use reinhardt::test::fixtures::postgres_with_migrations_from_dir;
	use reinhardt::test::fixtures::{ContainerAsync, GenericImage};
	use reinhardt_auth::AuthInfo;
	use reinhardt_auth::social::storage::SocialAccount;
	use rstest::*;
	use serial_test::serial;
	use uuid::Uuid;

	use crate::config::test_helpers::{ResolvedUrls, test_app};

	#[fixture]
	async fn db(
		test_app: (APIClient, ResolvedUrls),
	) -> (
		ContainerAsync<GenericImage>,
		Arc<DatabaseConnection>,
		APIClient,
		ResolvedUrls,
	) {
		let (client, urls) = test_app;
		let migrations_dir = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("migrations");
		let (container, conn) = postgres_with_migrations_from_dir(&migrations_dir)
			.await
			.expect("Failed to start PostgreSQL with migrations");
		(container, conn, client, urls)
	}

	async fn seed_user_with_password(username: &str, email: &str) -> Uuid {
		let mut user = User::new(
			username.to_string(),
			email.to_lowercase(),
			String::new(),
			String::new(),
			None,
			true,
			false,
			false,
		);
		user.set_password("test-password-1234").unwrap();
		User::objects().create(&user).await.expect("seed user").id
	}

	async fn seed_user_no_password(username: &str, email: &str) -> Uuid {
		let user = User::new(
			username.to_string(),
			email.to_lowercase(),
			String::new(),
			String::new(),
			None,
			true,
			false,
			false,
		);
		User::objects().create(&user).await.expect("seed user").id
	}

	async fn seed_link(user_id: Uuid, provider: &str, sub: &str) {
		let storage = OrmSocialAccountStorage::new();
		let now = chrono::Utc::now();
		let acc = SocialAccount {
			id: Uuid::now_v7(),
			user_id,
			provider: provider.to_string(),
			provider_user_id: sub.to_string(),
			email: Some(format!("{sub}@example.test")),
			display_name: Some(sub.to_string()),
			picture: None,
			access_token: String::new(),
			refresh_token: None,
			token_expires_at: now + Duration::hours(1),
			scopes: Vec::new(),
			created_at: now,
			updated_at: now,
		};
		storage.create(acc).await.expect("seed link");
	}

	#[rstest]
	#[tokio::test]
	async fn test_oauth_unlink_rejects_malformed_user_id_in_token() {
		// Arrange — an authenticated AuthState whose user_id field is not
		// a valid UUID. This can happen if a token was minted for a non-
		// User principal and must surface as 401, not 500.
		let auth = AuthInfo(AuthState::authenticated("not-a-uuid", false, true));

		// Act
		let result = oauth_unlink_original(Path("github".to_string()), auth).await;

		// Assert
		match result {
			Err(AppError::Authentication(msg)) => {
				assert!(
					msg.contains("invalid user_id in token"),
					"error message should explain the parse failure: {msg}"
				);
			}
			other => panic!("expected Authentication error, got {other:?}"),
		}
	}

	#[rstest]
	#[tokio::test(flavor = "multi_thread")]
	#[serial(database)]
	async fn test_oauth_unlink_returns_404_when_user_does_not_exist(
		#[future] db: (
			ContainerAsync<GenericImage>,
			Arc<DatabaseConnection>,
			APIClient,
			ResolvedUrls,
		),
	) {
		// Arrange — a syntactically valid UUID that does not match any
		// row in the users table.
		let (_c, _conn, _cli, _urls) = db.await;
		let ghost_id = Uuid::now_v7();
		let auth = AuthInfo(AuthState::authenticated(ghost_id.to_string(), false, true));

		// Act
		let result = oauth_unlink_original(Path("github".to_string()), auth).await;

		// Assert
		match result {
			Err(AppError::NotFound(msg)) => {
				assert_eq!(msg, "user not found");
			}
			other => panic!("expected NotFound, got {other:?}"),
		}
	}

	#[rstest]
	#[tokio::test(flavor = "multi_thread")]
	#[serial(database)]
	async fn test_oauth_unlink_returns_404_when_no_link_to_provider(
		#[future] db: (
			ContainerAsync<GenericImage>,
			Arc<DatabaseConnection>,
			APIClient,
			ResolvedUrls,
		),
	) {
		// Arrange — user exists but has no social link for any provider.
		let (_c, _conn, _cli, _urls) = db.await;
		let user_id = seed_user_with_password("unlink_nolink", "nolink@example.test").await;
		let auth = AuthInfo(AuthState::authenticated(user_id.to_string(), false, true));

		// Act
		let result = oauth_unlink_original(Path("github".to_string()), auth).await;

		// Assert
		match result {
			Err(AppError::NotFound(msg)) => {
				assert_eq!(msg, "no link to provider: github");
			}
			other => panic!("expected NotFound, got {other:?}"),
		}
	}

	#[rstest]
	#[tokio::test(flavor = "multi_thread")]
	#[serial(database)]
	async fn test_oauth_unlink_rejects_removing_last_sign_in_method(
		#[future] db: (
			ContainerAsync<GenericImage>,
			Arc<DatabaseConnection>,
			APIClient,
			ResolvedUrls,
		),
	) {
		// Arrange — OAuth-only user (no password) with a single social
		// link. Removing it would leave the account unreachable, so the
		// view must refuse with 422 instead of deleting.
		let (_c, _conn, _cli, _urls) = db.await;
		let user_id = seed_user_no_password("unlink_lockout", "lockout@example.test").await;
		seed_link(user_id, "github", "gh_lockout_1").await;
		let auth = AuthInfo(AuthState::authenticated(user_id.to_string(), false, true));

		// Act
		let result = oauth_unlink_original(Path("github".to_string()), auth).await;

		// Assert — Validation error AND the link is still present in
		// storage afterward, proving the refusal happened before the
		// delete.
		match result {
			Err(AppError::Validation(msg)) => {
				assert!(
					msg.contains("set a password before unlinking"),
					"lockout message should guide the user to set a password: {msg}"
				);
			}
			other => panic!("expected Validation, got {other:?}"),
		}
		let storage = OrmSocialAccountStorage::new();
		let links = storage.find_by_user(user_id).await.unwrap();
		assert_eq!(links.len(), 1, "lockout-protected link must NOT be deleted");
	}

	#[rstest]
	#[tokio::test(flavor = "multi_thread")]
	#[serial(database)]
	async fn test_oauth_unlink_succeeds_when_user_has_password(
		#[future] db: (
			ContainerAsync<GenericImage>,
			Arc<DatabaseConnection>,
			APIClient,
			ResolvedUrls,
		),
	) {
		// Arrange — user has a password, so removing the only social
		// link is safe and the lockout guard does not fire.
		let (_c, _conn, _cli, _urls) = db.await;
		let user_id = seed_user_with_password("unlink_ok", "ok@example.test").await;
		seed_link(user_id, "github", "gh_ok_1").await;
		let auth = AuthInfo(AuthState::authenticated(user_id.to_string(), false, true));

		// Act
		let response = oauth_unlink_original(Path("github".to_string()), auth)
			.await
			.expect("unlink should succeed when user has password");

		// Assert — 200 OK with JSON body, and the link is gone.
		assert_eq!(response.status, StatusCode::OK);
		let body =
			std::str::from_utf8(response.body.as_ref()).expect("response body must be utf-8");
		assert!(
			body.contains("\"success\":true") && body.contains("\"provider\":\"github\""),
			"response body should report success: {body}"
		);
		let storage = OrmSocialAccountStorage::new();
		let links = storage.find_by_user(user_id).await.unwrap();
		assert!(links.is_empty(), "link should have been deleted");
	}
}
