// reinhardt-migration-source: 1
// Generated by Reinhardt migrations.

use reinhardt::db::migrations::FieldType;
use reinhardt::db::migrations::prelude::*;
pub(super) fn migration() -> Migration {
	Migration::new("0002_add_constraint_auth_social_accounts", "auth")
		.add_operation(Operation::AddConstraint {
			table: "auth_social_accounts".to_string(),
			constraint_sql:
				"CONSTRAINT auth_social_account_user_provider_uniq UNIQUE (user_id, provider)"
					.to_string(),
		})
		.add_dependency("auth", "0001_initial")
		.atomic(true)
		.with_initial(None)
		.state_only(false)
		.database_only(false)
}
