//! Schema types for `reinhardt-cloud.toml` configuration file.
//!
//! This module defines the deserialization target for `reinhardt-cloud.toml` files
//! generated by `reinhardt-cloud init` and provides conversion to `ReinhardtAppSpec`.

use std::collections::BTreeMap;

use serde::{Deserialize, Serialize};

use crate::crd::{
	AuthSpec, BuildSpec as CrdBuildSpec, CacheBackend, CacheSpec, DatabaseEngine, DatabaseSpec,
	DeletionPolicy, GitProvider, HealthSpec, MailSpec, PreviewOverrides, PreviewSpec,
	ReinhardtAppSpec, ScaleMetric, ScaleSpec, ServicesSpec, SourceSpec, StorageBackend, StorageSpec,
	WebhookEvent, WebhookSpec, WorkerSpec,
};

/// Root configuration structure for `reinhardt-cloud.toml`
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct ReinhardtCloudToml {
	/// Application identity section
	pub app: AppSection,
	/// Database infrastructure configuration
	#[serde(default)]
	pub database: Option<DatabaseSection>,
	/// Authentication configuration
	#[serde(default)]
	pub auth: Option<AuthSection>,
	/// Health check configuration
	#[serde(default)]
	pub health: Option<HealthSection>,
	/// Service exposure configuration
	#[serde(default)]
	pub services: Option<ServicesSection>,
	/// Replica count configuration
	#[serde(default)]
	pub replicas: Option<ReplicasSection>,
	/// Autoscaling configuration
	#[serde(default)]
	pub scale: Option<ScaleSection>,
	/// Cache infrastructure configuration
	#[serde(default)]
	pub cache: Option<CacheSection>,
	/// Background worker configuration
	#[serde(default)]
	pub worker: Option<WorkerSection>,
	/// Object storage configuration
	#[serde(default)]
	pub storage: Option<StorageSection>,
	/// Mail (SMTP) configuration
	#[serde(default)]
	pub mail: Option<MailSection>,
	/// Git source and CI/CD pipeline configuration
	#[serde(default)]
	pub source: Option<SourceSection>,
	/// Environment variables as key-value pairs
	#[serde(default)]
	pub env: BTreeMap<String, String>,
}

/// Application identity section of `reinhardt-cloud.toml`
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct AppSection {
	/// Application name used as the CRD resource name
	pub name: String,
	/// Docker image to deploy
	pub image: String,
}

/// Database configuration section of `reinhardt-cloud.toml`
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct DatabaseSection {
	/// Database engine name (postgresql, mysql, sqlite)
	pub engine: String,
	/// Instance class (platform-specific, e.g., "db.t3.micro")
	pub instance_class: Option<String>,
	/// Storage size in GB
	pub storage_gb: Option<i32>,
	/// Engine version (e.g., "16" for PostgreSQL)
	pub version: Option<String>,
}

/// Authentication configuration section of `reinhardt-cloud.toml`
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct AuthSection {
	/// Whether JWT authentication is enabled
	#[serde(default)]
	pub jwt: bool,
}

/// Health check configuration section of `reinhardt-cloud.toml`
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct HealthSection {
	/// HTTP path for health checks
	pub path: Option<String>,
	/// Port for health checks
	pub port: Option<i32>,
	/// Interval between health checks in seconds
	pub interval_seconds: Option<i32>,
}

/// Service exposure configuration section of `reinhardt-cloud.toml`
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct ServicesSection {
	/// Service port
	pub port: Option<i32>,
	/// Target port on the container
	pub target_port: Option<i32>,
	/// Ingress hostname for external access
	pub ingress_host: Option<String>,
}

/// Replica count configuration section of `reinhardt-cloud.toml`
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct ReplicasSection {
	/// Number of desired replicas (defaults to 1)
	#[serde(default = "default_replica_count")]
	pub count: i32,
}

fn default_replica_count() -> i32 {
	1
}

/// Autoscaling configuration section of `reinhardt-cloud.toml`
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct ScaleSection {
	/// Minimum number of replicas
	pub min_replicas: Option<i32>,
	/// Maximum number of replicas
	pub max_replicas: Option<i32>,
	/// Metric to scale on (cpu, memory, rps)
	pub metric: Option<String>,
	/// Target value for the scaling metric
	pub target_value: Option<i32>,
}

/// Cache configuration section of `reinhardt-cloud.toml`
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct CacheSection {
	/// Cache backend type (defaults to "redis")
	#[serde(default = "default_cache_backend")]
	pub backend: String,
	/// Instance type (platform-specific)
	pub instance_type: Option<String>,
}

fn default_cache_backend() -> String {
	"redis".to_string()
}

/// Background worker configuration section of `reinhardt-cloud.toml`
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct WorkerSection {
	/// Number of worker processes (defaults to 4)
	#[serde(default = "default_concurrency")]
	pub concurrency: i32,
	/// Custom entrypoint command for worker
	pub command: Option<Vec<String>>,
}

fn default_concurrency() -> i32 {
	4
}

/// Object storage configuration section of `reinhardt-cloud.toml`
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct StorageSection {
	/// Storage backend (s3, gcs, pvc)
	pub backend: Option<String>,
	/// Bucket/volume name
	pub bucket: Option<String>,
}

/// Mail (SMTP) configuration section of `reinhardt-cloud.toml`
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct MailSection {
	/// SMTP host
	pub smtp_host: Option<String>,
	/// SMTP port
	pub smtp_port: Option<i32>,
}

/// Git source configuration section of `reinhardt-cloud.toml`
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct SourceSection {
	/// Git repository URL
	pub repository: String,
	/// Branch to track
	pub branch: Option<String>,
	/// Git hosting provider (github, gitlab)
	pub provider: Option<String>,
	/// Secret name containing Git credentials
	pub credentials_secret: Option<String>,
	/// Container build configuration
	#[serde(default)]
	pub build: Option<BuildSection>,
	/// Webhook receiver configuration
	#[serde(default)]
	pub webhook: Option<WebhookTomlSection>,
	/// Preview environment configuration
	#[serde(default)]
	pub preview: Option<PreviewTomlSection>,
}

/// Container build configuration section of `reinhardt-cloud.toml`
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct BuildSection {
	/// Container registry URL
	pub registry: Option<String>,
	/// Dockerfile path relative to context
	pub dockerfile: Option<String>,
	/// Build context directory
	pub context: Option<String>,
	/// Additional build arguments
	#[serde(default)]
	pub build_args: BTreeMap<String, String>,
}

/// Webhook configuration section of `reinhardt-cloud.toml`
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct WebhookTomlSection {
	/// Whether webhook receiving is enabled
	#[serde(default)]
	pub enabled: bool,
	/// Events to listen for (push, pull_request, tag)
	#[serde(default)]
	pub events: Vec<String>,
	/// Secret name containing the webhook signing secret
	pub secret_ref: Option<String>,
}

/// Preview environment configuration section of `reinhardt-cloud.toml`
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct PreviewTomlSection {
	/// Whether preview environments are enabled
	#[serde(default)]
	pub enabled: bool,
	/// Time-to-live for preview environments (e.g., "72h", "7d")
	pub ttl: Option<String>,
	/// URL template for preview environments
	pub url_template: Option<String>,
	/// Resource overrides for preview deployments
	#[serde(default)]
	pub overrides: Option<PreviewOverridesTomlSection>,
}

/// Preview resource overrides section of `reinhardt-cloud.toml`
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct PreviewOverridesTomlSection {
	/// Override replica count for preview
	pub replicas: Option<i32>,
}

impl ReinhardtCloudToml {
	/// Converts this configuration to a `ReinhardtAppSpec` for CRD creation.
	///
	/// String-based engine/backend/metric fields are mapped to their
	/// corresponding enum variants, falling back to sensible defaults
	/// for unrecognised values.
	pub fn to_reinhardt_app_spec(&self) -> ReinhardtAppSpec {
		ReinhardtAppSpec {
			image: self.app.image.clone(),
			replicas: self.replicas.as_ref().map(|r| r.count),
			database: self.database.as_ref().map(|d| DatabaseSpec {
				engine: match d.engine.as_str() {
					"mysql" => DatabaseEngine::Mysql,
					"sqlite" => DatabaseEngine::Sqlite,
					_ => DatabaseEngine::Postgresql,
				},
				instance_class: d.instance_class.clone(),
				storage_gb: d.storage_gb,
				version: d.version.clone(),
			}),
			health: self.health.as_ref().map(|h| HealthSpec {
				path: h.path.clone(),
				port: h.port,
				interval_seconds: h.interval_seconds,
			}),
			services: self.services.as_ref().map(|s| ServicesSpec {
				port: s.port,
				target_port: s.target_port,
				ingress_host: s.ingress_host.clone(),
			}),
			scale: self.scale.as_ref().map(|s| ScaleSpec {
				min_replicas: s.min_replicas,
				max_replicas: s.max_replicas,
				metric: s.metric.as_ref().map(|m| match m.as_str() {
					"memory" => ScaleMetric::Memory,
					"rps" => ScaleMetric::Rps,
					_ => ScaleMetric::Cpu,
				}),
				target_value: s.target_value,
			}),
			env: self.env.clone(),
			cache: self.cache.as_ref().map(|c| CacheSpec {
				// Only Redis is currently supported
				backend: CacheBackend::Redis,
				instance_type: c.instance_type.clone(),
			}),
			worker: self.worker.as_ref().map(|w| WorkerSpec {
				concurrency: Some(w.concurrency),
				command: w.command.clone(),
			}),
			auth: self.auth.as_ref().map(|a| AuthSpec {
				jwt: a.jwt,
				oauth: None,
			}),
			storage: self.storage.as_ref().map(|s| StorageSpec {
				backend: s.backend.as_ref().map(|b| match b.as_str() {
					"gcs" => StorageBackend::Gcs,
					"pvc" => StorageBackend::Pvc,
					_ => StorageBackend::S3,
				}),
				bucket: s.bucket.clone(),
			}),
			mail: self.mail.as_ref().map(|m| MailSpec {
				smtp_host: m.smtp_host.clone(),
				smtp_port: m.smtp_port,
				credentials_secret: None,
			}),
			pages: None,
			deletion_policy: DeletionPolicy::default(),
			features: Vec::new(),
			introspect: None,
			isolation: None,
			source: self.source.as_ref().map(|s| SourceSpec {
				repository: s.repository.clone(),
				branch: s.branch.clone(),
				provider: s.provider.as_ref().map(|p| match p.as_str() {
					"gitlab" => GitProvider::GitLab,
					_ => GitProvider::GitHub,
				}),
				credentials_secret: s.credentials_secret.clone(),
				build: s.build.as_ref().map(|b| CrdBuildSpec {
					dockerfile: b.dockerfile.clone(),
					context: b.context.clone(),
					registry: b.registry.clone(),
					build_args: b.build_args.clone(),
				}),
				webhook: s.webhook.as_ref().map(|w| WebhookSpec {
					enabled: w.enabled,
					events: w
						.events
						.iter()
						.filter_map(|e| match e.as_str() {
							"push" => Some(WebhookEvent::Push),
							"pull_request" => Some(WebhookEvent::PullRequest),
							"tag" => Some(WebhookEvent::Tag),
							_ => None,
						})
						.collect(),
					secret_ref: w.secret_ref.clone(),
				}),
				preview: s.preview.as_ref().map(|p| PreviewSpec {
					enabled: p.enabled,
					ttl: p.ttl.clone(),
					url_template: p.url_template.clone(),
					overrides: p.overrides.as_ref().map(|o| PreviewOverrides {
						replicas: o.replicas,
						database: None,
						cache: None,
					}),
				}),
			}),
		}
	}
}

#[cfg(test)]
mod tests {
	use super::*;
	use rstest::rstest;

	#[rstest]
	fn test_parse_minimal_reinhardt_cloud_toml() {
		// Arrange
		let toml_str = r#"
[app]
name = "my-app"
image = "my-app:latest"

[database]
engine = "postgresql"
"#;
		// Act
		let config: ReinhardtCloudToml = toml::from_str(toml_str).unwrap();
		// Assert
		assert_eq!(config.app.name, "my-app");
		assert_eq!(config.app.image, "my-app:latest");
		assert_eq!(config.database.unwrap().engine, "postgresql");
	}

	#[rstest]
	fn test_parse_full_reinhardt_cloud_toml() {
		// Arrange
		let toml_str = r#"
[app]
name = "full-app"
image = "full-app:v2"

[database]
engine = "postgresql"
instance_class = "db.t3.micro"
storage_gb = 50
version = "16"

[auth]
jwt = true

[health]
path = "/health"
port = 3000
interval_seconds = 15

[services]
port = 443
target_port = 3000
ingress_host = "app.example.com"

[replicas]
count = 3

[cache]
backend = "redis"

[worker]
concurrency = 8

[env]
CUSTOM_VAR = "custom_value"
"#;
		// Act
		let config: ReinhardtCloudToml = toml::from_str(toml_str).unwrap();
		// Assert
		assert_eq!(config.app.name, "full-app");
		assert_eq!(config.replicas.unwrap().count, 3);
		assert_eq!(config.cache.unwrap().backend, "redis");
		assert_eq!(config.worker.unwrap().concurrency, 8);
		assert_eq!(config.env.get("CUSTOM_VAR").unwrap(), "custom_value");
	}

	#[rstest]
	fn test_reinhardt_cloud_toml_to_reinhardt_app_spec() {
		// Arrange
		let config = ReinhardtCloudToml {
			app: AppSection {
				name: "test".into(),
				image: "test:v1".into(),
			},
			database: Some(DatabaseSection {
				engine: "postgresql".into(),
				..Default::default()
			}),
			auth: Some(AuthSection { jwt: true }),
			replicas: Some(ReplicasSection { count: 2 }),
			..Default::default()
		};
		// Act
		let spec = config.to_reinhardt_app_spec();
		// Assert
		assert_eq!(spec.image, "test:v1");
		assert_eq!(spec.replicas, Some(2));
		let db = spec.database.unwrap();
		assert_eq!(db.engine, DatabaseEngine::Postgresql);
		assert!(spec.auth.unwrap().jwt);
	}

	#[rstest]
	fn test_reinhardt_cloud_toml_defaults_produce_valid_spec() {
		// Arrange
		let config = ReinhardtCloudToml {
			app: AppSection {
				name: "minimal".into(),
				image: "minimal:latest".into(),
			},
			..Default::default()
		};
		// Act
		let spec = config.to_reinhardt_app_spec();
		// Assert
		assert_eq!(spec.image, "minimal:latest");
		assert!(spec.database.is_none());
		assert!(spec.cache.is_none());
		assert!(spec.worker.is_none());
		assert!(spec.auth.is_none());
		assert_eq!(spec.deletion_policy, DeletionPolicy::Retain);
	}

	#[rstest]
	fn test_parse_empty_toml_only_app_section() {
		// Arrange
		let toml_str = r#"
[app]
name = "minimal"
image = "minimal:latest"
"#;
		// Act
		let config: ReinhardtCloudToml = toml::from_str(toml_str).unwrap();
		// Assert
		assert_eq!(config.app.name, "minimal");
		assert!(config.database.is_none());
		assert!(config.auth.is_none());
		assert!(config.health.is_none());
		assert!(config.services.is_none());
		assert!(config.replicas.is_none());
		assert!(config.scale.is_none());
		assert!(config.cache.is_none());
		assert!(config.worker.is_none());
		assert!(config.storage.is_none());
		assert!(config.mail.is_none());
		assert!(config.env.is_empty());
	}

	#[rstest]
	fn test_parse_toml_unknown_fields_are_ignored() {
		// Arrange: serde's default behavior ignores unknown fields
		let toml_str = r#"
[app]
name = "test"
image = "test:v1"
unknown_key = "should be ignored"

[nonexistent_section]
foo = "bar"
"#;
		// Act
		let result: Result<ReinhardtCloudToml, _> = toml::from_str(toml_str);
		// Assert: unknown fields are silently ignored by serde default
		assert!(result.is_ok());
		assert_eq!(result.unwrap().app.name, "test");
	}

	#[rstest]
	fn test_invalid_engine_defaults_to_postgresql() {
		// Arrange
		let config = ReinhardtCloudToml {
			app: AppSection {
				name: "t".into(),
				image: "t:v1".into(),
			},
			database: Some(DatabaseSection {
				engine: "invalid_engine".into(),
				..Default::default()
			}),
			..Default::default()
		};
		// Act
		let spec = config.to_reinhardt_app_spec();
		// Assert
		assert_eq!(spec.database.unwrap().engine, DatabaseEngine::Postgresql);
	}

	#[rstest]
	fn test_scale_section_with_partial_fields() {
		// Arrange
		let toml_str = r#"
[app]
name = "scale-test"
image = "app:v1"

[scale]
min_replicas = 2
"#;
		// Act
		let config: ReinhardtCloudToml = toml::from_str(toml_str).unwrap();
		let spec = config.to_reinhardt_app_spec();
		// Assert
		let scale = spec.scale.unwrap();
		assert_eq!(scale.min_replicas, Some(2));
		assert!(scale.max_replicas.is_none());
		assert!(scale.metric.is_none());
		assert!(scale.target_value.is_none());
	}

	#[rstest]
	fn test_storage_section_s3_backend() {
		// Arrange
		let config = ReinhardtCloudToml {
			app: AppSection {
				name: "t".into(),
				image: "t:v1".into(),
			},
			storage: Some(StorageSection {
				backend: Some("s3".into()),
				bucket: Some("my-bucket".into()),
			}),
			..Default::default()
		};
		// Act
		let spec = config.to_reinhardt_app_spec();
		// Assert
		let storage = spec.storage.unwrap();
		assert_eq!(storage.backend, Some(StorageBackend::S3));
		assert_eq!(storage.bucket.as_deref(), Some("my-bucket"));
	}

	#[rstest]
	fn test_storage_section_gcs_backend() {
		// Arrange
		let config = ReinhardtCloudToml {
			app: AppSection {
				name: "t".into(),
				image: "t:v1".into(),
			},
			storage: Some(StorageSection {
				backend: Some("gcs".into()),
				bucket: None,
			}),
			..Default::default()
		};
		// Act
		let spec = config.to_reinhardt_app_spec();
		// Assert
		assert_eq!(spec.storage.unwrap().backend, Some(StorageBackend::Gcs));
	}

	#[rstest]
	fn test_storage_section_pvc_backend() {
		// Arrange
		let config = ReinhardtCloudToml {
			app: AppSection {
				name: "t".into(),
				image: "t:v1".into(),
			},
			storage: Some(StorageSection {
				backend: Some("pvc".into()),
				bucket: None,
			}),
			..Default::default()
		};
		// Act
		let spec = config.to_reinhardt_app_spec();
		// Assert
		assert_eq!(spec.storage.unwrap().backend, Some(StorageBackend::Pvc));
	}

	#[rstest]
	fn test_reinhardt_cloud_toml_mysql_engine() {
		// Arrange
		let config = ReinhardtCloudToml {
			app: AppSection {
				name: "t".into(),
				image: "t:v1".into(),
			},
			database: Some(DatabaseSection {
				engine: "mysql".into(),
				..Default::default()
			}),
			..Default::default()
		};
		// Act
		let spec = config.to_reinhardt_app_spec();
		// Assert
		assert_eq!(spec.database.unwrap().engine, DatabaseEngine::Mysql);
	}

	#[rstest]
	fn test_parse_source_section() {
		// Arrange
		let toml_str = r#"
[app]
name = "my-app"
image = "my-app:latest"

[source]
repository = "https://github.com/myorg/myapp"
branch = "main"
provider = "github"
credentials_secret = "git-creds"

[source.build]
registry = "ghcr.io/myorg"
dockerfile = "Dockerfile"
context = "."
"#;
		// Act
		let config: ReinhardtCloudToml = toml::from_str(toml_str).unwrap();
		// Assert
		let source = config.source.unwrap();
		assert_eq!(source.repository, "https://github.com/myorg/myapp");
		assert_eq!(source.branch.as_deref(), Some("main"));
		assert_eq!(source.provider.as_deref(), Some("github"));
		assert_eq!(source.credentials_secret.as_deref(), Some("git-creds"));
		let build = source.build.unwrap();
		assert_eq!(build.registry.as_deref(), Some("ghcr.io/myorg"));
		assert_eq!(build.dockerfile.as_deref(), Some("Dockerfile"));
		assert_eq!(build.context.as_deref(), Some("."));
	}

	#[rstest]
	fn test_parse_source_with_webhook_and_preview() {
		// Arrange
		let toml_str = r#"
[app]
name = "my-app"
image = "my-app:latest"

[source]
repository = "https://github.com/myorg/myapp"

[source.webhook]
enabled = true
events = ["push", "pull_request"]
secret_ref = "webhook-secret"

[source.preview]
enabled = true
ttl = "72h"
url_template = "{branch}.preview.example.com"

[source.preview.overrides]
replicas = 1
"#;
		// Act
		let config: ReinhardtCloudToml = toml::from_str(toml_str).unwrap();
		// Assert
		let source = config.source.unwrap();
		let webhook = source.webhook.unwrap();
		assert!(webhook.enabled);
		assert_eq!(webhook.events, vec!["push", "pull_request"]);
		assert_eq!(webhook.secret_ref.as_deref(), Some("webhook-secret"));
		let preview = source.preview.unwrap();
		assert!(preview.enabled);
		assert_eq!(preview.ttl.as_deref(), Some("72h"));
		assert_eq!(
			preview.url_template.as_deref(),
			Some("{branch}.preview.example.com")
		);
		assert_eq!(preview.overrides.unwrap().replicas, Some(1));
	}

	#[rstest]
	fn test_source_section_conversion_to_spec() {
		// Arrange
		let config = ReinhardtCloudToml {
			app: AppSection {
				name: "t".into(),
				image: "t:v1".into(),
			},
			source: Some(SourceSection {
				repository: "https://github.com/myorg/myapp".into(),
				branch: Some("develop".into()),
				provider: Some("gitlab".into()),
				credentials_secret: Some("git-creds".into()),
				build: Some(BuildSection {
					registry: Some("ghcr.io/myorg".into()),
					dockerfile: Some("Dockerfile".into()),
					context: Some(".".into()),
					build_args: BTreeMap::from([("MODE".into(), "release".into())]),
				}),
				webhook: Some(WebhookTomlSection {
					enabled: true,
					events: vec![
						"push".into(),
						"pull_request".into(),
						"tag".into(),
						"unknown_event".into(),
					],
					secret_ref: Some("wh-secret".into()),
				}),
				preview: Some(PreviewTomlSection {
					enabled: true,
					ttl: Some("48h".into()),
					url_template: Some("{branch}.dev.example.com".into()),
					overrides: Some(PreviewOverridesTomlSection {
						replicas: Some(2),
					}),
				}),
			}),
			..Default::default()
		};
		// Act
		let spec = config.to_reinhardt_app_spec();
		// Assert
		let source = spec.source.unwrap();
		assert_eq!(source.repository, "https://github.com/myorg/myapp");
		assert_eq!(source.branch.as_deref(), Some("develop"));
		assert_eq!(source.provider, Some(GitProvider::GitLab));
		assert_eq!(source.credentials_secret.as_deref(), Some("git-creds"));
		let build = source.build.unwrap();
		assert_eq!(build.registry.as_deref(), Some("ghcr.io/myorg"));
		assert_eq!(build.dockerfile.as_deref(), Some("Dockerfile"));
		assert_eq!(build.build_args.get("MODE").map(|s| s.as_str()), Some("release"));
		let webhook = source.webhook.unwrap();
		assert!(webhook.enabled);
		// unknown_event should be filtered out
		assert_eq!(webhook.events.len(), 3);
		assert_eq!(webhook.events[0], WebhookEvent::Push);
		assert_eq!(webhook.events[1], WebhookEvent::PullRequest);
		assert_eq!(webhook.events[2], WebhookEvent::Tag);
		let preview = source.preview.unwrap();
		assert!(preview.enabled);
		assert_eq!(preview.ttl.as_deref(), Some("48h"));
		let overrides = preview.overrides.unwrap();
		assert_eq!(overrides.replicas, Some(2));
		assert!(overrides.database.is_none());
		assert!(overrides.cache.is_none());
	}

	#[rstest]
	fn test_invalid_provider_defaults_to_github() {
		// Arrange
		let config = ReinhardtCloudToml {
			app: AppSection {
				name: "t".into(),
				image: "t:v1".into(),
			},
			source: Some(SourceSection {
				repository: "https://example.com/repo".into(),
				provider: Some("bitbucket".into()),
				..Default::default()
			}),
			..Default::default()
		};
		// Act
		let spec = config.to_reinhardt_app_spec();
		// Assert
		assert_eq!(spec.source.unwrap().provider, Some(GitProvider::GitHub));
	}

	#[rstest]
	fn test_no_source_section_produces_none() {
		// Arrange
		let config = ReinhardtCloudToml {
			app: AppSection {
				name: "t".into(),
				image: "t:v1".into(),
			},
			..Default::default()
		};
		// Act
		let spec = config.to_reinhardt_app_spec();
		// Assert
		assert!(spec.source.is_none());
	}
}
