# Generated by reinhardt-cloud. Do not edit manually.
FROM rust:1.94.1-bookworm AS chef
RUN cargo install cargo-chef
WORKDIR /app
COPY . .
RUN cargo chef prepare --recipe-path recipe.json

FROM rust:1.94.1-bookworm AS builder
RUN cargo install cargo-chef
WORKDIR /app
COPY --from=chef /app/recipe.json recipe.json
RUN cargo chef cook --release --recipe-path recipe.json
COPY . .
RUN cargo build --release -p my-app

FROM rust:1.94.1-bookworm AS wasm
RUN rustup target add wasm32-unknown-unknown
RUN cargo install wasm-bindgen-cli@0.2.100
WORKDIR /app
COPY . .
RUN cargo build --release --target wasm32-unknown-unknown --lib -p my-app
RUN wasm-bindgen --out-dir /wasm-dist --target web target/wasm32-unknown-unknown/release/my_app.wasm

FROM builder AS assets
COPY --from=wasm /wasm-dist /build/wasm-dist
WORKDIR /app
ENV REINHARDT_ENV=production
RUN /app/target/release/manage buildstatic --pages-dir /build/wasm-dist --pages-entry my_app.js --pages-document index.html

FROM debian:bookworm-slim AS runtime
RUN apt-get update && \
    apt-get install -y --no-install-recommends ca-certificates tini && \
    rm -rf /var/lib/apt/lists/*
RUN useradd --create-home appuser
WORKDIR /app
COPY --from=builder /app/target/release/my-app /app/
COPY --from=builder /app/target/release/manage /app/
COPY --from=assets /app/static /app/static
RUN chown -R appuser:appuser /app
# Run as non-root
USER appuser
ENV RUST_LOG=info \
    PATH=/app:$PATH \
    REINHARDT_ENV=production
EXPOSE 8000
ENTRYPOINT ["tini", "--", "/app/my-app"]
