// reinhardt-migration-source: 1
// Generated by Reinhardt migrations.

use reinhardt::db::migrations::FieldType;
use reinhardt::db::migrations::prelude::*;
pub(super) fn migration() -> Migration {
	Migration::new("0001_initial".to_string(), "deployments".to_string())
		.add_operation(Operation::CreateTable {
			name: "deployments".to_string(),
			columns: vec![
				ColumnDefinition::new("cluster_id".to_string(), FieldType::BigInteger)
					.with_not_null(true)
					.with_unique(false)
					.with_primary_key(false)
					.with_auto_increment(false)
					.with_default(None)
					.with_generated(None)
					.with_domain_option(None),
				ColumnDefinition::new("created_at".to_string(), FieldType::TimestampTz)
					.with_not_null(true)
					.with_unique(false)
					.with_primary_key(false)
					.with_auto_increment(false)
					.with_default(None)
					.with_generated(None)
					.with_domain_option(None),
				ColumnDefinition::new("id".to_string(), FieldType::BigInteger)
					.with_not_null(true)
					.with_unique(false)
					.with_primary_key(true)
					.with_auto_increment(true)
					.with_default(None)
					.with_generated(None)
					.with_domain_option(None),
				ColumnDefinition::new("image".to_string(), FieldType::VarChar(512u32))
					.with_not_null(true)
					.with_unique(false)
					.with_primary_key(false)
					.with_auto_increment(false)
					.with_default(None)
					.with_generated(None)
					.with_domain_option(None),
				ColumnDefinition::new("organization_id".to_string(), FieldType::BigInteger)
					.with_not_null(true)
					.with_unique(false)
					.with_primary_key(false)
					.with_auto_increment(false)
					.with_default(None)
					.with_generated(None)
					.with_domain_option(None),
				ColumnDefinition::new("project_name".to_string(), FieldType::VarChar(255u32))
					.with_not_null(true)
					.with_unique(false)
					.with_primary_key(false)
					.with_auto_increment(false)
					.with_default(None)
					.with_generated(None)
					.with_domain_option(None),
				ColumnDefinition::new("project_yaml".to_string(), FieldType::VarChar(65535u32))
					.with_not_null(false)
					.with_unique(false)
					.with_primary_key(false)
					.with_auto_increment(false)
					.with_default(None)
					.with_generated(None)
					.with_domain_option(None),
				ColumnDefinition::new("status".to_string(), FieldType::VarChar(50u32))
					.with_not_null(true)
					.with_unique(false)
					.with_primary_key(false)
					.with_auto_increment(false)
					.with_default(Some("'pending'".to_string()))
					.with_generated(None)
					.with_domain_option(None),
				ColumnDefinition::new("updated_at".to_string(), FieldType::TimestampTz)
					.with_not_null(true)
					.with_unique(false)
					.with_primary_key(false)
					.with_auto_increment(false)
					.with_default(None)
					.with_generated(None)
					.with_domain_option(None),
			],
			constraints: vec![
				Constraint::ForeignKey {
					name: "fk_deployments_cluster_id".to_string(),
					columns: vec!["cluster_id".to_string()],
					referenced_table: "clusters".to_string(),
					referenced_columns: vec!["id".to_string()],
					on_delete: ForeignKeyAction::Restrict,
					on_update: ForeignKeyAction::Cascade,
					deferrable: None,
				},
				Constraint::ForeignKey {
					name: "fk_deployments_organization_id".to_string(),
					columns: vec!["organization_id".to_string()],
					referenced_table: "organizations".to_string(),
					referenced_columns: vec!["id".to_string()],
					on_delete: ForeignKeyAction::Cascade,
					on_update: ForeignKeyAction::NoAction,
					deferrable: None,
				},
			],
			without_rowid: None,
			interleave_in_parent: None,
			partition: None,
		})
		.add_operation(Operation::CreateIndex {
			table: "deployments".to_string(),
			columns: vec!["cluster_id".to_string()],
			unique: false,
			index_type: None,
			where_clause: None,
			concurrently: false,
			expressions: None,
			mysql_options: None,
			operator_class: None,
		})
		.add_operation(Operation::CreateIndex {
			table: "deployments".to_string(),
			columns: vec!["organization_id".to_string()],
			unique: false,
			index_type: None,
			where_clause: None,
			concurrently: false,
			expressions: None,
			mysql_options: None,
			operator_class: None,
		})
		.add_dependency("clusters".to_string(), "0001_initial".to_string())
		.add_dependency("organizations".to_string(), "0001_initial".to_string())
		.atomic(true)
		.with_initial(Some(true))
		.state_only(false)
		.database_only(false)
}
