// reinhardt-migration-source: 1
// Generated by Reinhardt migrations.

use reinhardt::db::migrations::FieldType;
use reinhardt::db::migrations::prelude::{
	ColumnDefinition, Constraint, ForeignKeyAction, Migration, Operation,
};
pub(super) fn migration() -> Migration {
	Migration::new(
		"0002_cloud_environment_allocation_create_index_c_and_more",
		"cluster",
	)
	.add_operation(Operation::CreateTable {
		name: "cloud_environment_allocation".to_string(),
		columns: vec![
			ColumnDefinition::new("cluster_id", FieldType::Uuid)
				.with_not_null(true)
				.with_unique(false)
				.with_primary_key(false)
				.with_auto_increment(false)
				.with_default(None)
				.with_generated(None)
				.with_domain_option(None),
			ColumnDefinition::new("environment_id", FieldType::Uuid)
				.with_not_null(true)
				.with_unique(false)
				.with_primary_key(false)
				.with_auto_increment(false)
				.with_default(None)
				.with_generated(None)
				.with_domain_option(None),
			ColumnDefinition::new("id", FieldType::Uuid)
				.with_not_null(true)
				.with_unique(false)
				.with_primary_key(true)
				.with_auto_increment(false)
				.with_default(None)
				.with_generated(None)
				.with_domain_option(None),
			ColumnDefinition::new("replica_limit", FieldType::Integer)
				.with_not_null(true)
				.with_unique(false)
				.with_primary_key(false)
				.with_auto_increment(false)
				.with_default(Some("10".to_string()))
				.with_generated(None)
				.with_domain_option(None),
		],
		constraints: vec![
			Constraint::ForeignKey {
				name: "fk_cloud_environment_allocation_cluster_id".to_string(),
				columns: vec!["cluster_id".to_string()],
				referenced_table: "cloud_cluster_cluster".to_string(),
				referenced_columns: vec!["id".to_string()],
				on_delete: ForeignKeyAction::Restrict,
				on_update: ForeignKeyAction::NoAction,
				deferrable: None,
			},
			Constraint::ForeignKey {
				name: "fk_cloud_environment_allocation_environment_id".to_string(),
				columns: vec!["environment_id".to_string()],
				referenced_table: "cloud_environment".to_string(),
				referenced_columns: vec!["id".to_string()],
				on_delete: ForeignKeyAction::Cascade,
				on_update: ForeignKeyAction::NoAction,
				deferrable: None,
			},
			Constraint::Unique {
				name: "cloud_environment_allocation_environment_id_uniq_8b9c9376".to_string(),
				columns: vec!["environment_id".to_string()],
			},
		],
		without_rowid: None,
		interleave_in_parent: None,
		partition: None,
	})
	.add_operation(Operation::CreateIndex {
		table: "cloud_environment_allocation".to_string(),
		columns: vec!["cluster_id".to_string()],
		unique: false,
		index_type: None,
		where_clause: None,
		concurrently: false,
		expressions: None,
		mysql_options: None,
		operator_class: None,
	})
	.add_operation(Operation::AddColumn {
		table: "cloud_cluster_cluster".to_string(),
		column: ColumnDefinition::new("cpu_autoscaling", FieldType::Boolean)
			.with_not_null(true)
			.with_unique(false)
			.with_primary_key(false)
			.with_auto_increment(false)
			.with_default(Some("false".to_string()))
			.with_generated(None)
			.with_domain_option(None),
		mysql_options: None,
	})
	.add_operation(Operation::AddColumn {
		table: "cloud_cluster_cluster".to_string(),
		column: ColumnDefinition::new("dns", FieldType::Boolean)
			.with_not_null(true)
			.with_unique(false)
			.with_primary_key(false)
			.with_auto_increment(false)
			.with_default(Some("false".to_string()))
			.with_generated(None)
			.with_domain_option(None),
		mysql_options: None,
	})
	.add_operation(Operation::AddColumn {
		table: "cloud_cluster_cluster".to_string(),
		column: ColumnDefinition::new("ingress", FieldType::Boolean)
			.with_not_null(true)
			.with_unique(false)
			.with_primary_key(false)
			.with_auto_increment(false)
			.with_default(Some("false".to_string()))
			.with_generated(None)
			.with_domain_option(None),
		mysql_options: None,
	})
	.add_operation(Operation::AddColumn {
		table: "cloud_cluster_cluster".to_string(),
		column: ColumnDefinition::new("namespace_issuer", FieldType::Boolean)
			.with_not_null(true)
			.with_unique(false)
			.with_primary_key(false)
			.with_auto_increment(false)
			.with_default(Some("false".to_string()))
			.with_generated(None)
			.with_domain_option(None),
		mysql_options: None,
	})
	.add_operation(Operation::AddColumn {
		table: "cloud_cluster_cluster".to_string(),
		column: ColumnDefinition::new("rootless_builds", FieldType::Boolean)
			.with_not_null(true)
			.with_unique(false)
			.with_primary_key(false)
			.with_auto_increment(false)
			.with_default(Some("false".to_string()))
			.with_generated(None)
			.with_domain_option(None),
		mysql_options: None,
	})
	.add_dependency("cluster", "0001_initial")
	.add_dependency("project", "0002_cloud_environment_desired_runtime")
	.atomic(true)
	.with_initial(None)
	.state_only(false)
	.database_only(false)
}
